User-agent: *
Disallow: /assets/
Disallow: /static/
Disallow: /plugin/
Disallow: /tinymce/
Disallow: /_ctoweb/
Disallow: /php*
Disallow: /*?*
Sitemap: https://www.51cto.com/sitemap/google/index.xml
Sitemap: https://www.51cto.com/sitemap/google/index_detail.xml
Sitemap: https://www.51cto.com/sitemap/google/list.xml
Sitemap: https://www.51cto.com/sitemap/google/others.xml
