User-agent: *
Disallow: /article
Disallow: /site-explorer/ajax/
Allow: /site-explorer/$
Disallow: /site-explorer/*
Allow: /link-intersect/$
Disallow: /link-intersect/*
Disallow: /v4*
Disallow: /blog/*?s=*
Disallow: /seo/for/*?*draft
Disallow: /blog/top-bing-searches/
Disallow: /blog/top-youtube-searches/
Disallow: /academy/*?*draft
Disallow: /team-new
