User-agent: Twitterbot
Disallow: /
Allow: /$
Allow: /shr*
Allow: /images/*
User-agent: *
Allow: /
Disallow: /404
Disallow: /500
Disallow: /auth
Disallow: /embed/*
Disallow: /temporary_marketing_proxy/*
Disallow: /forgot
Disallow: /internal/*
Disallow: /invite/l?inviteId=*&inviteToken=*
Disallow: /msa
Disallow: /shr*
Disallow: /sso/login
Disallow: /tbl*
Disallow: /?try=*
Disallow: /*?referralCode=*
Disallow: /?utm_source=*
Sitemap: https://airtable.com/sitemap.xml
