user-agent: *
disallow: /showcase.php/
disallow: /SendMailToUser.php*
disallow: /report_item.php*
disallow: /events/clicks
disallow: /offer/
disallow: /ape
disallow: /payments
disallow: /recommendations/
disallow: /cart-aggregator/
disallow: /favourites/
disallow: /usertraits/
disallow: /mediation/
disallow: *snapshot=*
disallow: /language-dispatcher
disallow: *&source=allegro.com&welcome=1&shippingCountry=US*
disallow: /login/auth
disallow: /auth/oauth/authorize
disallow: /produkt/warianty/
disallow: /uzytkownik*&*&*
