<<<<<<< HEAD
User-agent: *
Disallow: /*?*
Disallow: /member/index*
Disallow: /share/*
Disallow: /*php*
Disallow: /file_down/
Disallow: *html/download_error.html
Disallow: /user_center_v1/
Disallow: /doclist/list-*-1-1.html
Disallow: /doclist/list-*-1-2.html
Disallow: /doclist/list-*-1-3.html
Disallow: /search.html
Disallow: /uhome/*-*.html
Disallow: /uhome/*-*-*.html
=======
User-agent: *
Disallow: /*?*
Disallow: /member/index*
Disallow: /share/*
Disallow: /*php*
Disallow: /file_down/
Disallow: *html/download_error.html
Disallow: /user_center_v1/
Disallow: /doclist/list-*-1-1.html
Disallow: /doclist/list-*-1-2.html
Disallow: /doclist/list-*-1-3.html
Disallow: /search.html
Disallow: /uhome/*-*.html
Disallow: /uhome/*-*-*.html
>>>>>>> c881411106adf687acaf306d655ca150e70ee17f
