User-agent: *
Sitemap: https://www.boyfriendtv.com/sitemaps.xml
Disallow: /*ajax-
Disallow: /search/
Disallow: /search-img/
Disallow: /adv-search.php
Disallow: /adv-search/
Disallow: /login.php
Disallow: /models/?
Disallow: /*cgi-bin/
Disallow: /best-galleries
Disallow: /best-videos
Disallow: /*lang=
Disallow: /embed/
Disallow: /model/*/fans
Disallow: /documents/
User-agent: AhrefsBot
Disallow: /