User-agent: *
Disallow: /likeit/*
Disallow: /unlikeit/*
Disallow: /jclike/*
Disallow: /jcunlike/*
Disallow: /loadmore?*
Disallow: /pageroll?v=*
Disallow: /weatheri/
Disallow: /cpnw?*
Disallow: /stools?*
Disallow: /hits?pkid=*
Disallow: /*view=*
Disallow: /*task=*
Disallow: /*tmpl=*
Disallow: /*preview=*
Disallow: /*print=*
Disallow: /*Itemid=*

Sitemap: https://www.delgarm.com/sitemap.xml