User-agent: *

Disallow: /ja-jp/*/spd/
Disallow: /ja-jp/*/povw/
Disallow: /ja-jp/*/productdetailstxn/
Disallow: /learn/jp/
Disallow: /ja-jp/shop/*/ar/8228
Disallow: /ja-jp/shop/*/ar/8225
Disallow: /ja-jp/shop/*/ar/8343
Disallow: /ja-jp/shop/*/ar/8231
Disallow: /ja-jp/shop/*/ar/8225
Disallow: /ja-jp/shop/*/sf/xps-2-in-1

Disallow: /en-ca/*/povw/
Disallow: /learn/ca/
Disallow: /en-ca/shop/*/sf/xps-2-in-1
Disallow: /fr-ca/shop/2-in-1-pcs/sf/xps-2-in-1
Disallow: /en-ca/shop/sfc/sf/security
Disallow: /en-ca/shop/servers-storage-networking/sf/poweredge-mseries-blade-interconnects
Disallow: /en-ca/shop/workstations/sf/dell-canvas
Disallow: /en-ca/shop/gateways-embedded-computing/sf/embedded-box-pcs
Disallow: /en-ca/shop/gateways-embedded-computing/sf/edge-gateway
Disallow: /en-ca/shop/servers-storage-networking/sf/security
Disallow: /fr-ca/shop/entreprise/sf/access-platforms
Disallow: /fr-ca/shop/cty/sf/security
Disallow: /fr-ca/shop/*/sf/edge-gateway
Disallow: /fr-ca/shop/*/sf/embedded-box-pcs
Disallow: /en-ca/shop/productdetailstxn/networking-n2000-series
Disallow: /en-ca/shop/productdetailstxn/poweredge-r730
Disallow: /fr-ca/shop/povw/powervault-ml6010
Disallow: /fr-ca/shop/povw/powervault-tl2000
Disallow: /fr-ca/shop/povw/sonicwall-nsa-series
Disallow: /fr-ca/shop/povw/sonicwall-gms-series
Disallow: /fr-ca/shop/povw/poweredge-r730
Disallow: /fr-ca/shop/povw/equallogic-ps6210-series
Disallow: /fr-ca/shop/povw/poweredge-r730xd

Disallow: /zh-tw/shop/cty/pdp/spd/vxrail-g560
Disallow: /zh-tw/shop/cty/pdp/spd/poweredge-r330
Disallow: /zh-tw/shop/enterprise-products/poweredge-t130/spd/poweredge-t130
Disallow: /zh-tw/shop/enterprise-products/poweredge-r330/spd/poweredge-r330
Disallow: /zh-tw/shop/cty/pdp/spd/poweredge-t130
Disallow: /zh-tw/shop/enterprise-products/poweredge-r730xd/spd/poweredge-r730xd
Disallow: /zh-tw/shop/productdetailstxn/equallogic-ps6210-series
Disallow: /zh-tw/shop/productdetailstxn/equallogic-ps6610-series
Disallow: /zh-tw/shop/productdetailstxn/equallogic-ps4210-series
Disallow: /da-dk/shop/productdetailstxn/equallogic-ps-m4110
Disallow: /da-dk/shop/productdetailstxn/smart-fabric-director
Disallow: /da-dk/shop/productdetailstxn/poweredge-m830
Disallow: /da-dk/shop/productdetailstxn/equallogic-ps6210-series
Disallow: /da-dk/shop/productdetailstxn/poweredge-r830
Disallow: /da-dk/shop/productdetailstxn/equallogic-ps4210-series
Disallow: /da-dk/shop/productdetailstxn/poweredge-r730xd
Disallow: /da-dk/shop/productdetailstxn/dell-openmanage-network-manager
Disallow: /da-dk/shop/productdetailstxn/poweredge-r530
Disallow: /en-uk/*/povw/
Disallow: /de-ch/*/productdetailstxn/
Disallow: /es-es/*/productdetailstxn/
Disallow: /it-it/*/productdetailstxn/
Disallow: /learn/dk/
Disallow: /learn/at/
Disallow: /learn/ch/
Disallow: /learn/de/
Disallow: /learn/ie/
Disallow: /learn/uk/
Disallow: /learn/es/
Disallow: /learn/be/
Disallow: /learn/ch/
Disallow: /learn/fr/
Disallow: /learn/it/
Disallow: /learn/be/
Disallow: /learn/nl/
Disallow: /learn/no/
Disallow: /learn/se/
Disallow: /en-uk/member/
Disallow: /fr-fr/member/
Disallow: /sv-se/member/
Disallow: /nl-nl/member/
Disallow: /pt-br/*/productdetailstxn/
Disallow: /learn/pt/
Disallow: /pt-br/shop/monitores-para-o-dia-a-dia/ar/8405
Disallow: /pt-br/shop/endpoints-e-software-wyse/sf/thin-clients
Disallow: /pt-br/shop/povw/poweredge-r730
Disallow: /pt-br/shop/notebooks-dell/inspiron-14-3000/spd/inspiron-14-3480-laptop/ci3480w107brnbd
Disallow: /pt-br/shop/notebooks-dell/novo-inspiron-13-7000/spd/inspiron-13-7391-laptop/ci7391w1012brw
Disallow: /pt-br/shop/notebooks-dell/inspiron-14-3000/spd/inspiron-14-3481-laptop/ci3480w107brnbd
Disallow: /pt-br/shop/notebooks-dell/novo-vostro-14-5000/spd/vostro-14-5402-laptop/v5402w6001w
Disallow: /pt-br/shop/laptop-2-em-1/notebook-vostro-14-5000/spd/vostro-14-5402-laptop/v5402w6001w
Disallow: /pt-br/shop/notebooks-dell/notebook-vostro-14-5000/spd/vostro-14-5402-laptop/v5402w6001w
Disallow: /pt-br/shop/cty/pdp/spd/vostro-14-5402-laptop/v5402w6001w
Disallow: /fr-fr/shop/*/ac/4011
Disallow: /da-dk/shop/2-in-1-laptops/sf/xps-2-in-1
Disallow: /de-ch/shop/2-in-1-pcs/sf/xps-2-in-1
Disallow: /de-de/shop/2-in-1-laptops/sf/xps-2-in-1
Disallow: /en-uk/shop/2-in-1-laptops/sf/xps-2-in-1
Disallow: /en-uk/shop/2-in-1-laptops/sf/xps-2-in-1/xps-13-2-in-1s
Disallow: /es-es/shop/portÃ¡tiles-2-en-1/sf/xps-2-in-1
Disallow: /fr-ch/shop/2-in-1-pcs/sf/xps-2-in-1
Disallow: /it-it/shop/notebook-2-in-1/sf/xps-2-in-1
Disallow: /no-no/shop/2-i-1-pc-er/sf/xps-2-in-1
Disallow: /da-dk/shop/dell-tablets/sf/latitude-2-in-1
Disallow: /da-dk/shop/dell-tablets/sf/rugged-tablets
Disallow: /da-dk/shop/dell-tablets/sf/inspiron-2-in-1
Disallow: /da-dk/shop/dell-tablets/sf/xps-2-in-1
Disallow: /da-dk/shop/gateways-embedded-computing/sf/embedded-box-pcs
Disallow: /da-dk/shop/dell-tablets/sf/chromebook-2-in-1
Disallow: /da-dk/shop/isv-certificeret-og-optimeret-workstation/sf/dell-canvas
Disallow: /de-ch/shop/tablet-pcs/sf/xps-2-in-1
Disallow: /de-ch/shop/tablet-pcs/sf/rugged-tablets
Disallow: /de-ch/shop/gateways-und-embedded-datenverarbeitung/sf/embedded-box-pcs
Disallow: /de-ch/shop/tablet-pcs/sf/inspiron-2-in-1
Disallow: /de-ch/shop/workstations/sf/dell-canvas
Disallow: /de-ch/shop/tablet-pcs/sf/chromebook-2-in-1
Disallow: /en-uk/shop/cty/sf/embedded-box-pcs
Disallow: /en-uk/shop/workstations/sf/dell-canvas
Disallow: /en-uk/shop/gateways-embedded-computing/sf/embedded-box-pcs
Disallow: /en-uk/shop/2-in-1-business-laptops/sf/inspiron-2-in-1
Disallow: /en-uk/shop/2-in-1-business-laptops/sf/inspiron-2-in-1/inspiron-14-2-in-1-laptops
Disallow: /en-uk/shop/2-in-1-business-laptops/sf/latitude-2-in-1
Disallow: /en-uk/shop/2-in-1-business-laptops/sf/latitude-2-in-1/latitude-3000-series-2-in-1s
Disallow: /en-uk/shop/2-in-1-business-laptops/sf/rugged-tablets
Disallow: /en-uk/shop/2-in-1-business-laptops/sf/xps-2-in-1
Disallow: /es-es/shop/tabletas-dell/sf/inspiron-2-in-1
Disallow: /es-es/shop/tabletas-dell/sf/xps-2-in-1
Disallow: /es-es/shop/puntos-finales-y-software-de-wyse/sf/wyse-applicances
Disallow: /es-es/shop/tabletas-dell/sf/latitude-2-in-1
Disallow: /es-es/shop/tabletas-dell/sf/rugged-tablets
Disallow: /fr-ch/shop/tablettes-dell/sf/inspiron-2-in-1
Disallow: /fr-ch/shop/tablettes-dell/sf/rugged-tablets
Disallow: /fr-ch/shop/tablettes-dell/sf/latitude-2-in-1
Disallow: /it-it/shop/gateway-ed-elaborazione-incorporata/sf/embedded-box-pcs
Disallow: /it-it/shop/tablet-dell/sf/rugged-tablets
Disallow: /it-it/shop/tablet-dell/sf/inspiron-2-in-1
Disallow: /it-it/shop/tablet-dell/sf/xps-2-in-1
Disallow: /it-it/shop/tablet-dell/sf/chromebook-2-in-1
Disallow: /it-it/shop/tablet-dell/sf/latitude-2-in-1
Disallow: /no-no/shop/wyse-sluttpunkter-og-programvare/sf/wyse-applicances
Disallow: /no-no/shop/dells-nettbrett/sf/latitude-2-in-1
Disallow: /no-no/shop/dells-nettbrett/sf/inspiron-2-in-1
Disallow: /no-no/shop/dells-nettbrett/sf/rugged-tablets
Disallow: /no-no/shop/dells-nettbrett/sf/chromebook-2-in-1
Disallow: /no-no/shop/isv-sertifisert-og-optimert-for-arbeidsstasjon/sf/dell-canvas
Disallow: /no-no/shop/dells-nettbrett/sf/xps-2-in-1
Disallow: /no-no/shop/gateways-embedded-computing/sf/embedded-box-pcs
Disallow: /sv-se/shop/sfc/sf/vostro-desktops
Disallow: /en-ie/shop/2-in-1-pcs/sf/xps-2-in-1
Disallow: /nl-nl/shop/2-in-1-laptops/sf/xps-2-in-1
Disallow: /de-at/shop/2-in-1-pcs/sf/xps-2-in-1
Disallow: /fr-fr/shop/ordinateurs-portables-2-en-1/sf/xps-2-in-1
Disallow: /es-es/shop/cty/sf/xps-2-in-1
Disallow: /sv-se/shop/bÃ¤rbara-2-i-1-datorer/sf/xps-2-in-1
Disallow: /fr-be/shop/2-in-1-pcs/sf/xps-2-in-1
Disallow: /nl-be/shop/2-in-1-laptops/sf/xps-2-in-1
Disallow: /fr-be/shop/tablettes-dell/sf/inspiron-2-in-1
Disallow: /nl-nl/shop/cty/sf/embedded-box-pcs
Disallow: /nl-be/shop/dell-tablets/sf/latitude-2-in-1
Disallow: /fr-fr/shop/ordinateurs-portables-2-en1/sf/xps-2-in-1
Disallow: /de-de/shop/2-in-1-laptops/sf/latitude-2-in-1
Disallow: /sv-se/shop/cty/sf/vostro-desktops
Disallow: /de-de/shop/workstations/sf/dell-canvas
Disallow: /de-at/shop/dell-tablets/sf/xps-2-in-1
Disallow: /de-de/shop/gateways-und-embedded-datenverarbeitung/sf/embedded-box-pcs
Disallow: /fr-be/shop/tablettes/sf/inspiron-2-in-1
Disallow: /de-ch/shop/sfc/sf/security
Disallow: /de-de/shop/produkte-fur-netzwerk-und-daten-sicherheit/sf/security
Disallow: /nl-be/shop/wyse-endpoints-end-software/sf/wyse-applicances
Disallow: /nl-be/shop/gateways-embedded-computing/sf/embedded-box-pcs
Disallow: /sv-se/shop/dell-workstations/sf/dell-canvas
Disallow: /fr-fr/shop/tablettes-nbsp-dell/sf/xps-2-in-1
Disallow: /nl-nl/shop/tablets/sf/latitude-2-in-1
Disallow: /en-ie/shop/sfc/sf/security
Disallow: /de-de/shop/2-in-1-pcs/sf/latitude-2-in-1
Disallow: /fr-fr/shop/cty/sf/embedded-box-pcs
Disallow: /fr-ch/shop/sfc/sf/security
Disallow: /nl-be/shop/dell-tablets/sf/chromebook-2-in-1
Disallow: /en-ie/shop/tablets-and-2-in-1-laptops/sf/rugged-tablets
Disallow: /de-de/shop/cty/sf/embedded-box-pcs
Disallow: /es-es/shop/tabletas-dell/sf/chromebook-2-in-1
Disallow: /en-ie/shop/servers-storage-networking/sf/security
Disallow: /de-ch/shop/cty/sf/security
Disallow: /en-uk/shop/tablets-and-2-in-1-laptops/sf/latitude-2-in-1
Disallow: /sv-se/shop/dell-surfplattor/sf/rugged-tablets
Disallow: /de-at/shop/cty/sf/embedded-box-pcs
Disallow: /de-at/shop/tablet-pcs/sf/inspiron-2-in-1
Disallow: /sv-se/shop/desktops-all-in-one-pcs/sf/vostro-desktops
Disallow: /it-it/shop/cty/sf/embedded-box-pcs
Disallow: /en-ie/shop/tablets-and-2-in-1-laptops/sf/chromebook-2-in-1
Disallow: /nl-nl/shop/gateways-embedded-computing/sf/embedded-box-pcs
Disallow: /de-at/shop/gateways-und-embedded-datenverarbeitung/sf/embedded-box-pcs
Disallow: /sv-se/shop/cty/sf/embedded-box-pcs
Disallow: /da-dk/shop/cty/sf/xps-2-in-1
Disallow: /fr-be/shop/tablettes-dell/sf/rugged-tablets
Disallow: /fr-fr/shop/tablettes-dell/sf/xps-2-in-1
Disallow: /es-es/shop/cty/sf/embedded-box-pcs
Disallow: /es-es/shop/cty/sf/latitude-2-in-1
Disallow: /de-at/shop/tablet-pcs/sf/latitude-2-in-1
Disallow: /sv-se/shop/dell-surfplattor/sf/chromebook-2-in-1
Disallow: /en-uk/shop/2-in-1-business-laptops/sf/chromebook-2-in-1
Disallow: /nl-nl/shop/tablets/sf/xps-2-in-1
Disallow: /de-de/shop/2-in-1-pcs/sf/xps-2-in-1
Disallow: /it-it/shop/dell-tablets/sf/latitude-2-in-1
Disallow: /de-de/shop/2-in-1-laptops/sf/chromebook-2-in-1
Disallow: /en-ie/shop/gateways-embedded-computing/sf/embedded-box-pcs
Disallow: /de-at/shop/gateways-embedded-computing/sf/embedded-box-pcs
Disallow: /fr-fr/shop/ordinateurs-portables-2-en1/sf/latitude-2-in-1
Disallow: /fr-fr/shop/sfc/sf/security
Disallow: /no-no/shop/cty/sf/embedded-box-pcs
Disallow: /de-de/shop/sfc/sf/security
Disallow: /it-it/shop/cty/sf/latitude-2-in-1
Disallow: /nl-nl/shop/tablets/sf/rugged-tablets
Disallow: /fr-fr/shop/ordinateurs-portables-2-en1/sf/rugged-tablets
Disallow: /de-ch/shop/gateways-embedded-computing/sf/embedded-box-pcs
Disallow: /de-at/shop/povw/ml3-tape-library
Disallow: /da-dk/shop/povw/embedded-box-pc-3000
Disallow: /da-dk/shop/povw/networking-n4000-series
Disallow: /da-dk/shop/povw/poweredge-r420
Disallow: /da-dk/shop/povw/dell-canvas-kv2718d
Disallow: /da-dk/shop/povw/networking-wireless-ruckus-controllers
Disallow: /da-dk/shop/povw/poweredge-r720
Disallow: /en-nz/shop/tv-deals/ar/8224
Disallow: /en-nz/shop/gaming-deals/ar/8244
Disallow: /en-nz/shop/gateways-embedded-computing/sf/embedded-box-pcs
Disallow: /en-nz/shop/cty/sf/embedded-box-pcs
Disallow: /en-nz/shop/2-in-1-pcs/sf/precision-2-in-1
Disallow: /en-nz/shop/gateways-embedded-computing/sf/edge-gateway
Disallow: /ko-kr/shop/productdetailstxn/networking-x-series
Disallow: /ko-kr/shop/productdetailstxn/equallogic-ps-m4110
Disallow: /ko-kr/shop/productdetailstxn/networking-n2000-series
Disallow: /ko-kr/shop/productdetailstxn/dell-openmanage-network-manager
Disallow: /ko-kr/shop/productdetailstxn/smart-fabric-director
Disallow: /ko-kr/shop/povw/equallogic-ps-m4110
Disallow: /ko-kr/shop/productdetailstxn/equallogic-ps6210-series
Disallow: /ko-kr/shop/productdetailstxn/equallogic-ps4210-series
Disallow: /ko-kr/shop/productdetailstxn/equallogic-ps6610-series

Disallow: /koa/search
Disallow: /Search/
Disallow: /search/
Disallow: */learn/search*
Disallow: /support/search/
Disallow: /support/Search/
Disallow: /content/products/compare.aspx/cloudedge?c=us&l=en&s=biz
Disallow: */identity
Disallow: */survey.aspx
Disallow: */serviceselection
Disallow: */Identity
Disallow: */Serviceselection
Allow: /*/compare.aspx*s=biz*
Allow: /*/compare.aspx*s=hied*
Allow: /*/compare.aspx*s=hea*
Allow: /*/compare.aspx*s=fed*
Allow: /*/compare.aspx*s=slg*
Allow: /*.js$
Allow: /*.css$
Allow: /*/compare.aspx*s=k12*
Disallow: */api/
Allow: /api/feeds.svc/rss/newsroom-press-releases/
Disallow: /*cs=45
Disallow: /*cs=04sp1
Disallow: /*cs=04sp2
Disallow: /*cs=04sp3
Disallow: /*cs=04sp4
Disallow: /*cs=04sp5
Disallow: /*cs=04sp6
Disallow: /*cs=04sp7
Disallow: /*cs=04sp8
Disallow: /*cs=04sp9
Disallow: /*cs=04sp10
Disallow: /*cs=04sp11
Disallow: /*cs=04sp12
Disallow: /*cs=04sp13
Disallow: /*cs=04sp14
Disallow: /*cs=04sp15
Disallow: /*cs=04sp16
Disallow: /*cs=04SP1
Disallow: /*cs=04SP2
Disallow: /*cs=04SP3
Disallow: /*cs=04SP4
Disallow: /*cs=04SP5
Disallow: /*cs=04SP6
Disallow: /*cs=04SP7
Disallow: /*cs=04SP8
Disallow: /*cs=04SP9
Disallow: /*cs=04SP10
Disallow: /*cs=04SP11
Disallow: /*cs=04SP12
Disallow: /*cs=04SP13
Disallow: /*cs=04SP14
Disallow: /*cs=04SP15
Disallow: /*cs=04SP16
Disallow: /*cs=OWR08
Disallow: /*cs=08
Disallow: /*cs=owr08
Disallow: /*~f=lg
Disallow: /support/home/cassette.axd/*
Disallow: /*/compare.aspx
Disallow: /*/menu.aspx
Disallow: /*/superview.aspx
Disallow: /*/productdetails.aspx*s=gen*
Disallow: /*/productdetail.aspx*s=gen*
Disallow: /*/pd.aspx*s=corp*
Disallow: /*/productdetails.aspx*s=corp*
Disallow: /*/productdetail.aspx*s=corp*
Disallow: /*/cp.aspx*s=corp*
Disallow: /*/ct.aspx*s=corp*
Disallow: /*/pd.aspx*s=gen*
Disallow: /*/cp.aspx*s=gen*
Disallow: /*/ct.aspx*s=gen*
Disallow: /*/pd.aspx*s=dfo*
Disallow: /*/productdetails.aspx*s=dfo*
Disallow: /*/productdetail.aspx*s=dfo*
Disallow: /*/cp.aspx*s=dfo*
Disallow: /*/ct.aspx*s=dfo*
Disallow: /*/category.aspx*s=dfo*
Disallow: /*/compare.aspx*s=dfo*
Disallow: /*/category.aspx*s=gen*
Disallow: /*/category.aspx*s=corp*
Disallow: /*/brand.aspx*s=corp*
Disallow: /*/brand.aspx*s=gen*
Disallow: /*/brand.aspx*s=dfo*
Disallow: /*/popproductdetails.aspx*s=gen*
Disallow: /*/popproductdetail.aspx*s=gen*
Disallow: /*/popproductdetails.aspx*s=corp*
Disallow: /*/popproductdetail.aspx*s=corp*
Disallow: /*/popproductdetails.aspx*s=dfo*
Disallow: /*/popproductdetail.aspx*s=dfo*
Disallow: /content/topics/segtopic.aspx/contact			
Disallow: /br/empresa/p/test_buddy_shopno_page_waterk
Disallow: /br/p/test_buddy_shopno_page_waterx
Disallow: /fr/p/inspiron-duo/pd
Disallow: /uk/business/p/*/fs$
Disallow: /uk/p/*/fs$
Disallow: /uk/p/shipsfast-deals?cs=ukdhs1		
Disallow: /nl/bedrijven/p/*/fs$
Disallow: /nl/p/*/fs$		
Disallow: /us/p/alienware-laptops
Disallow: /learn/*/*/*/mse-assets/navigation-diagnose
Disallow: /support/home/*/*/*/Diagnostics/*  
Disallow: /support/home/*/*/*/Drivers/DownloadList/* 
Disallow: /support/home/*/*/*/Drivers/DriversList/* 
Disallow: /support/home/*/*/*/Drivers/EmailSubscription/* 
Disallow: /support/home/*/*/*/Drivers/OneClick/*
Disallow: /learn/us/en/rc968571/
Disallow: /*/cart/*
Disallow: /*/buy/*
Disallow: */csbapi/
Disallow: /us/partner/*
Disallow: /us/*/chn/*
Disallow: /us/partners/*
Disallow: /us/en/partner/*
Disallow: /*/ed/*
Disallow: /*?c=ed*
Disallow: /*&c=ed*
Disallow: /*?*svcTag=5MGSLL1*
Disallow: /support/manuals/*/*/*/flyout/
Disallow: /support/csbapi/
Disallow: /*addScript$
Disallow: *t:cp=
Disallow: *t:ac=
Disallow: /support/clientconnection/
Disallow: /support/*/tab_mob/
Disallow: *bvstate=
Disallow: /*styles/index.less
Disallow: /*quickview-template.html
Disallow: /*quickview
Disallow: /*updateProfile
Disallow: /*url$
Disallow: /*owl.less
Disallow: /*owlCustom.less
Disallow: /*/pdr/
Disallow: /community/forums/forumtopicprintpage
Disallow: /community/ideas/ideaprintpage
Disallow: /community/blogs/blogarticleprintpage
Disallow: /community/tkb/allarticlesprintpage
Disallow: /community/tkb/articleprintpage
Disallow: /community/help/faqpage
Disallow: /community/forums/usersonlinepage
Disallow: /community/forums/recentpostspage
Disallow: /community/util/componentrenderpage
Disallow: /community/tkb/articlehistorypage
Disallow: /community/forums/replypage
Disallow: /community/forums/postpage
Disallow: /community/notes/composepage
Disallow: /community/notes/privatenotespage/tab/compose
Disallow: /community/notes/v1_1/privatenotespage/tab/compose
Disallow: /community/notifications/notifymoderatorpage
Disallow: /community/vjauj58549/rss
Disallow: /community/*?t:ac=
Disallow: /community/*&t:ac=
Disallow: /community/*:lightboxrendercomponent?
Disallow: /community/*:lightboxrendercomponent&
Disallow: /community/*:lightboxrendercomponent/
Disallow: /community/*?ticket=
Disallow: /community/*&ticket=
Disallow: /community/*nobounce
Disallow: /community/auth/
Disallow: /community/plugins/common/feature/oauth/
Disallow: /community/plugins/common/feature/oauth2sso/
Disallow: /community/plugins/common/feature/saml/
Disallow: /community/plugins/common/feature/openidconnectsso/
Disallow: /community/plugins/common/feature/openidsso/
Disallow: /preferences/em/
Disallow: */hk-dell-outlet
Disallow: /storagehelp/ 
Disallow: /en-au/outlet/shop/*/*/
Disallow: /en-au/outlet/work/shop/*/*/
Disallow: /en-au/outlet/*?
Disallow: /*/member/*mpn-sitemap
Disallow: /*-*/home/
Disallow: /support/coveo-dell/*
Disallow: /support/components/*
Disallow: /support/article{lwp}/*
Disallow: /en-ca.$
Disallow: */en-cg
Disallow: */en-lu
Disallow: */en-ga
Disallow: */en-gr
Disallow: */en-ar
Disallow: */en-cl
Disallow: */en-co
Disallow: */en-de
Disallow: */en-pe
Disallow: */en-ve
Disallow: */en-fi
Disallow: */en-hu
Disallow: */en-it
Disallow: */en-pt
Disallow: */en-ro
Disallow: */en-rs
Disallow: */en-ua
Disallow: */en-tr
Disallow: */en-ch
Disallow: */en-jp
Disallow: */en-kr
Disallow: */en-br
Disallow: */en-fr
Disallow: */en-dk
Disallow: */en-es
Disallow: */en-cn
Disallow: */en-be
Disallow: */en-cd
Disallow: */en-mx
Disallow: */en-nl
Disallow: */en-pl
Disallow: */es-us
Disallow: */en-se
Disallow: */en-no
Disallow: */en-cz
Disallow: */en-at
Allow: */home/*/product-support/servicetag/*/configuration*
Disallow: /qrl/
Disallow: /QRL/
Disallow: /support/kbdoc/*/printview/
Disallow: /learn/jp/ja/jpbsd1/campaigns/coupon-promo-sb-af
Disallow: */Search/*
Disallow: */search/*
Disallow: /support/*/servicetag/*
Disallow: /support/*/ServiceTag/*
Disallow: /support/Diagnostics/*
Disallow: /support/diagnostics/*
Disallow: */kbdoc/*/000183218/*
Disallow: */kbdoc/*/000183220/*
Disallow: */kbdoc/*/000183222/*
Disallow: */kbdoc/*/000183223/*
Disallow: */kbdoc/*/000183273/*
Disallow: */kbdoc/*/000183274/*
Disallow: */kbdoc/*/000183276/*
Disallow: */kbdoc/*/000183277/*
Disallow: */kbdoc/*/000183278/*
Disallow: /zh-cn/outlet/shop/*/*/
Disallow: /zh-cn/outlet/work/shop/*/*/
Disallow: /zh-cn/outlet/*?
Disallow: /community/*autocomplete$
Disallow: /support/*/chat/*
Disallow: /de-de/outlet/shop/*/*/
Disallow: /de-de/outlet/work/shop/*/*/
Disallow: /de-de/outlet/*?
Disallow: */gaming/performance/
Disallow: /en-pk/
Disallow: /en-ph/
Disallow: /en-id/
Disallow: /en-vn/
Disallow: /en-th/
Disallow: /en-al/
Disallow: /en-ba/
Disallow: /en-bg/
Disallow: /en-hr/
Disallow: /en-ee/
Disallow: /en-gh/
Disallow: /en-is/
Disallow: /en-lv/
Disallow: /en-ly/
Disallow: /en-lt/
Disallow: /en-mk/
Disallow: /en-ng/
Disallow: /en-yu/
Disallow: /en-si/
Disallow: /fr-cg/
Disallow: /fr-ga/
Disallow: /hu-hu/
Disallow: /ro-ro/
Disallow: /ru-ru/
Disallow: /fr-sn/
Disallow: /tr-tr/
Disallow: /ru-ua/
Disallow: /ru-rs/
Disallow: /fr-ed/
Disallow: /en-ed/
Disallow: /fr-cd/
Disallow: /en-ai/
Disallow: /en-ag/
Disallow: /en-aw/
Disallow: /en-bs/
Disallow: /en-bb/
Disallow: /en-bz/
Disallow: /en-bm/
Disallow: /en-bo/
Disallow: /en-vg/
Disallow: /en-ky/
Disallow: /en-cr/
Disallow: /en-dm/
Disallow: /en-do/
Disallow: /en-ec/
Disallow: /en-sv/
Disallow: /en-gd/
Disallow: /en-gt/
Disallow: /en-gy/
Disallow: /en-ht/
Disallow: /en-hn/
Disallow: /en-jm/
Disallow: /en-an/
Disallow: /en-ni/
Disallow: /en-pa/
Disallow: /en-py/
Disallow: /en-pr/
Disallow: /en-kn/
Disallow: /en-lc/
Disallow: /en-vc/
Disallow: /en-sr/
Disallow: /en-tt/
Disallow: /en-tc/
Disallow: /en-vi/
Disallow: /es-ai/
Disallow: /es-ag/
Disallow: /es-aw/
Disallow: /es-bs/
Disallow: /es-bb/
Disallow: /es-bz/
Disallow: /es-bm/
Disallow: /es-bo/
Disallow: /es-vg/
Disallow: /es-ky/
Disallow: /es-cr/
Disallow: /es-dm/
Disallow: /es-do/
Disallow: /es-ec/
Disallow: /es-sv/
Disallow: /es-gd/
Disallow: /es-gt/
Disallow: /es-gy/
Disallow: /es-ht/
Disallow: /es-hn/
Disallow: /es-jm/
Disallow: /es-an/
Disallow: /es-ni/
Disallow: /es-pa/
Disallow: /es-py/
Disallow: /es-pr/
Disallow: /es-kn/
Disallow: /es-lc/
Disallow: /es-vc/
Disallow: /es-sr/
Disallow: /es-tt/
Disallow: /es-tc/
Disallow: /es-vi/
Disallow: /*appliedRefinements=
Disallow: /*appliedrefinements=
Allow: /*/sr/*?appliedRefinements= 
Allow: /*/sr/*?appliedrefinements=
Disallow: /*/sr/*?appliedRefinements=*,*
Disallow: /*/sr/*?appliedrefinements=*,*
Allow: /*/ar/4009?appliedRefinements=2828
Allow: /*/ar/*?appliedRefinements= 
Allow: /*/ar/*?appliedrefinements=
Disallow: /*/ar/*?appliedRefinements=*,*
Disallow: /*/ar/*?appliedrefinements=*,*
Disallow: */member
Disallow: */mpp/
Disallow: */member/*?appliedRefinements=
Disallow: */member/*?appliedrefinements=
Allow: */member/*/cp/
Allow: */mpp/*/cp/
Allow: */member/cp/
Allow: */member/lp/
Disallow: /community/*inlinemessagereplyeditor
Disallow: /community/*?tid=
Disallow: /community/*custom.grz.top-contributor-ep
Disallow: /community/*recommendedcontenttaplet:lazyrender
Disallow: /en-gb
Disallow: */perspectives/
Disallow: */blog/
Allow: /en-uk/dt/
Allow: /en-au/dt/
Allow: /en-ca/dt/
Allow: /en-hk/dt/
Allow: /en-in/dt/
Allow: /en-ie/dt/
Allow: /en-my/dt/
Allow: /en-nz/dt/
Allow: /en-sg/dt/
Allow: /en-us/dt/
Allow: /en-uk/blog/
Allow: /en-au/blog/
Allow: /en-ca/blog/
Allow: /en-hk/blog/
Allow: /en-in/blog/
Allow: /en-ie/blog/
Allow: /en-my/blog/
Allow: /en-nz/blog/
Allow: /en-sg/blog/
Allow: /en-us/blog/
Allow: /en-uk/perspectives/
Allow: /en-au/perspectives/
Allow: /en-ca/perspectives/
Allow: /en-hk/perspectives/
Allow: /en-in/perspectives/
Allow: /en-ie/perspectives/
Allow: /en-my/perspectives/
Allow: /en-nz/perspectives/
Allow: /en-sg/perspectives/
Allow: /en-us/perspectives/
Allow:/fr-ca/dt/
Allow:/zh-cn/dt/
Allow:/ja-jp/dt/
Allow:/de-de/dt/
Allow:/fr-fr/dt/
Allow:/sv-se/dt/
Allow:/es-es/dt/
Allow:/de-ch/dt/
Allow:/fr-ch/dt/
Allow:/pt-br/dt/
Allow:/nl-nl/dt/
Allow:/de-at/dt/
Allow:/nl-be/dt/
Allow:/fr-be/dt/
Allow:/da-dk/dt/
Allow:/it-it/dt/
Allow:/no-no/dt/
Allow:/pl-pl/dt/
Allow:/zh-hk/dt/
Allow:/zh-tw/dt/
Allow:/ko-kr/dt/
Allow:/fr-ca/blog/
Allow:/zh-cn/blog/
Allow:/ja-jp/blog/
Allow:/de-de/blog/
Allow:/fr-fr/blog/
Allow:/sv-se/blog/
Allow:/es-es/blog/
Allow:/de-ch/blog/
Allow:/fr-ch/blog/
Allow:/pt-br/blog/
Allow:/nl-nl/blog/
Allow:/de-at/blog/
Allow:/nl-be/blog/
Allow:/fr-be/blog/
Allow:/da-dk/blog/
Allow:/it-it/blog/
Allow:/no-no/blog/
Allow:/pl-pl/blog/
Allow:/zh-hk/blog/
Allow:/zh-tw/blog/
Allow:/ko-kr/blog/
Allow:/fr-ca/perspectives/
Allow:/zh-cn/perspectives/
Allow:/ja-jp/perspectives/
Allow:/de-de/perspectives/
Allow:/fr-fr/perspectives/
Allow:/sv-se/perspectives/
Allow:/es-es/perspectives/
Allow:/de-ch/perspectives/
Allow:/fr-ch/perspectives/
Allow:/pt-br/perspectives/
Allow:/nl-nl/perspectives/
Allow:/de-at/perspectives/
Allow:/nl-be/perspectives/
Allow:/fr-be/perspectives/
Allow:/da-dk/perspectives/
Allow:/it-it/perspectives/
Allow:/no-no/perspectives/
Allow:/pl-pl/perspectives/
Allow:/zh-hk/perspectives/
Allow:/zh-tw/perspectives/
Allow:/ko-kr/perspectives/
Disallow: */dt/*.php$
Disallow: */dt/*/configuration-page.htm
Disallow: */dt/*/testing/
Disallow: */dt/*/teammembers/
Disallow: */dt/*/gobig
Disallow: */blog/*.php$
Disallow: */blog/*/configuration-page.htm
Disallow: */blog/*/testing/
Disallow: */blog/*/teammembers/
Disallow: */blog/*/gobig
Disallow: */perspectives/*.php$
Disallow: */perspectives/*/configuration-page.htm
Disallow: */perspectives/*/testing/
Disallow: */perspectives/*/teammembers/
Disallow: */perspectives/*/gobig
Disallow: */corporate/newsroom-test.htm
Disallow: */corporate/karen-quintos.htm
Disallow: /uploads/alm-cache/
Disallow: /wp-uploads/alm-cache/
Disallow: /wp-admin/admin-ajax.php
Disallow: /support/sitealerts/*-*/
Disallow: */dt/
Disallow: /en-my/*/productdetailstxn/
Disallow: /en-my/shop/enterprise-products/sf/security
Disallow: /en-my/shop/enterprise-products/r7415-2ru-server-amd/spd/poweredge-r7415
Disallow: /en-my/shop/dell-tablets/sf/xps-2-in-1
Disallow: /en-my/shop/dell-tablets/sf/latitude-2-in-1
Disallow: /en-my/shop/cty/powerconnect-6248p-ethernet-switch/spd/powerconnect-6248p
Disallow: /en-my/shop/enterprise/sf/infiniband-switches
Disallow: /en-my/shop/cty/powerconnect-w-clearpass100-visitor-management-solution/spd/powerconnect-w-amigopod-100
Disallow: /en-my/shop/cty/dell-networking-6200-series-switches/spd/powerconnect-6200-series
Disallow: /en-my/shop/povw/poweredge-r730
Disallow: /en-my/shop/cty/powerconnect-6224f-switch/spd/powerconnect-6224f
Disallow: /en-my/shop/servers-storage-networking/sf/security
Disallow: /en-my/shop/povw/powervault-me4024
Disallow: /en-my/shop/cty/dell-powerconnect-6224-details/spd/powerconnect-6224
Disallow: /en-my/shop/dell-tablets/sf/inspiron-2-in-1
Disallow: /en-my/shop/2-in-1-laptops/sf/xps-2-in-1
Disallow: /en-my/shop/2-in-1-laptops/sf/inspiron-2-in-1
Disallow: /en-my/shop/gateways-embedded-computing/sf/embedded-box-pcs
Disallow: /en-my/shop/cty/broadcom-netxtreme-ii-5708-dual-port-ethernet-mezzanine-card-with-toe-for-dell-poweredge-m1000e-series-blade-servers/spd/broadcom-netxtremeii-5708-mez
Disallow: /en-my/shop/dell-tablets/sf/chromebook-2-in-1
Disallow: /en-sg/*/povw/
Disallow: /en-sg/*/productdetailstxn/
Disallow: /en-sg/shop/business-pcs-desktop-computers/sr/desktops/g-series
Disallow: /en-sg/shop/*/sf/infiniband-switches
Disallow: /en-sg/shop/*/sf/embedded-box-pcs
Disallow: /en-sg/shop/*/sf/infiniband-switches
Disallow: /en-sg/shop/*/sf/latitude-2-in-1
Disallow: /en-sg/shop/*/sf/alienware-laptops
Disallow: /en-sg/shop/*/sf/security
Disallow: /en-sg/shop/*/sf/inspiron-2-in-1
Disallow: /en-sg/shop/*/sf/xps-2-in-1
Disallow: /en-sg/shop/cty/poweredge-fd332-storage-sled/spd/poweredge-fd332
Disallow: /en-sg/shop/cty/pdp/spd/sonicwall-enforced-anti-virus
Disallow: /en-sg/shop/enterprise-products/openmanage-network-manager/spd/dell-openmanage-network-manager
Disallow: /en-sg/shop/enterprise-products/new-sd-wan-edge-3000/spd/sd-wan-edge-3000
Disallow: /en-sg/shop/cty/poweredge-fc430-server-sled/spd/poweredge-fc430
Disallow: /en-sg/shop/enterprise-products/r7415-2ru-server-amd/spd/poweredge-r7415
Disallow: /en-sg/shop/enterprise-products/vrealize-business/spd/vmware-vrealize-business
Disallow: /en-sg/shop/enterprise-products/realize-log-insight/spd/vmware-vrealize-log-insight
Disallow: /en-sg/shop/enterprise-products/c6420-two-socket-server-node-intel/spd/poweredge-c6420
Disallow: /en-sg/shop/enterprise-products/openmanage-for-system-center/spd/openmanage-microsoft
Disallow: /en-sg/shop/enterprise-products/vcenter-server/spd/vmware-vcenter
Disallow: /en-sg/shop/enterprise-products/r640-1ru-server-intel/spd/poweredge-r640fv
Disallow: /en-sg/shop/enterprise-products/poweredge-fx/spd/poweredge-fx
Disallow: /en-sg/shop/cloud-client/wyse-management-suite/spd/wyse-wms
Disallow: /en-sg/shop/smart-home-deals/ar/8382
Disallow: /en-sg/shop/limited-time-sale/ar/8386
Disallow: /en-sg/shop/pc-accessories-sales/ar/8405
Disallow: /en-sg/shop/audio-deals/ar/8342
Disallow: /en-sg/shop/docking-stations-deals/ar/8345
Disallow: /en-sg/shop/computer-accessories-deals/ar/8228
Disallow: /en-sg/shop/accessories/ar/8405
Disallow: /en-sg/shop/parts-upgrades-deals/ar/8343
Disallow: /en-sg/shop/gaming-deals/ar/8244
Disallow: /en-sg/shop/tablet-deals/ar/8349
Disallow: /en-sg/shop/printer-deals/ar/8229
Disallow: /en-sg/shop/bags-cases-deals/ar/8348
Disallow: /en-sg/shop/accessories-sale/ar/8405
Disallow: /en-sg/shop/software-deals/ar/8230
Disallow: /en-sg/shop/electronics-sales/ar/8406
Disallow: /en-sg/shop/camera-deals/ar/8227
Disallow: /en-sg/shop/networking-deals/ar/8232
Disallow: /en-sg/shop/tv-deals/ar/8224
Disallow: /en-sg/shop/wearable-deals/ar/8344
Disallow: /en-sg/shop/smarthomedeals/ar/8382
Disallow: /en-sg/shop/smartphone-deals/ar/8226
Disallow: /en-sg/shop/projector-deals/ar/8234
Disallow: /en-sg/shop/accessories/ar/8386
Disallow: /en-sg/shop/storage-deals/ar/8231
Disallow: /*.php
Disallow: /zh-cn/shop/äºåä¸æ¬/sf/xps-2-in-1
Disallow: /en-hk/*/spd/
Disallow: /en-hk/shop/monitor-deals/ar/8225
Disallow: /en-hk/shop/bags-cases/ar/8348
Disallow: /en-hk/shop/åå½©åªæ /ar/8244
Disallow: /en-hk/shop/printer-deals/ar/8229
Disallow: /en-hk/shop/software-deals/ar/8230
Disallow: /en-hk/shop/gaming-deals/ar/8244
Disallow: /en-hk/shop/computer-accessories-deals/ar/8228
Disallow: /en-hk/shop/projector-deals/ar/8234
Disallow: /en-hk/shop/power/ar/8346
Disallow: /en-hk/shop/electronic-and-accessory-deals/ar/8245
Disallow: /en-hk/shop/camera-deals/ar/8227
Disallow: /en-hk/shop/wearable/ar/8344
Disallow: /en-hk/shop/tv-deals/ar/8224
Disallow: /en-hk/shop/tablet-deals/ar/8349
Disallow: /en-hk/shop/storage-deals/ar/8231
Disallow: /en-hk/shop/audio/ar/8342
Disallow: /en-hk/shop/parts-upgrades/ar/8343
Disallow: /en-hk/shop/povw/poweredge-r230
Disallow: /en-hk/shop/povw/storage-sc9000
Disallow: /en-hk/shop/povw/poweredge-t130
Disallow: /en-hk/shop/povw/poweredge-m1000e
Disallow: /en-hk/shop/povw/smart-fabric-director
Disallow: /en-hk/shop/povw/poweredge-t330
Disallow: /en-hk/shop/2-in-1-laptops/sf/latitude-2-in-1
Disallow: /en-hk/shop/pc-accessories-sales/ar/8405
Disallow: /en-hk/shop/povw/networking-wireless-ruckus-software
Disallow: /en-hk/shop/povw/poweredge-m830
Disallow: /en-hk/shop/povw/networking-wireless-ruckus-controllers
Disallow: /en-hk/shop/povw/equallogic-ps6610-series
Disallow: /en-hk/shop/productdetailstxn/poweredge-t30
Disallow: /en-hk/shop/productdetailstxn/poweredge-m630
Disallow: /en-hk/shop/povw/poweredge-t30
Disallow: /en-hk/shop/productdetailstxn/equallogic-ps4210-series
Disallow: /en-hk/shop/networking-deals/ar/8232
Disallow: /en-hk/shop/smart-home-deals/ar/8382
Disallow: /en-hk/shop/povw/poweredge-m630
Disallow: /en-hk/shop/monitors-monitor-accessories/ar/8225
Disallow: /en-hk/shop/docking-stations/ar/8345
Disallow: /en-hk/shop/partsbytype/printeraccessories
Disallow: /en-hk/shop/productdetailstxn/smart-fabric-director
Disallow: /en-hk/shop/productdetailstxn/equallogic-ps6210-series
Disallow: /zh-hk/*/spd/
Disallow: /zh-hk/shop/accessories/deals
Disallow: /zh-hk/shop/å¹³æ¿é»è¦äº¤æ/ar/8349
Disallow: /zh-hk/shop/åå½©åªæ /ar/8244
Disallow: /zh-hk/shop/é¡¯ç¤ºå¨äº¤æ/ar/8225
Disallow: /zh-hk/shop/*/ar/8234
Disallow: /zh-hk/shop/ç®±å/ar/8348
Disallow: /zh-hk/shop/electronic-and-accessory-deals/ar/8245
Disallow: /zh-hk/shop/é»è¦éä»¶/ar/8228
Disallow: /zh-hk/shop/æå°æ©äº¤æ/ar/8229
Disallow: /zh-hk/shop/é»å­åéä»¶åªæ /ar/8245
Disallow: /zh-hk/shop/åé ç«/ar/8345
Disallow: /zh-hk/shop/*/ar/8231
Disallow: /zh-hk/shop/*/ar/8382
Disallow: /zh-hk/shop/*/ar/8342
Disallow: /zh-hk/shop/*/ar/8227
Disallow: /zh-hk/shop/*/ar/8230
Disallow: /zh-hk/shop/æºè½å®¶å±åªæ /ar/8382
Disallow: /zh-hk/shop/*/ar/8348
Disallow: /zh-hk/shop/accessories/apd/452-BCSI
Disallow: /zh-hk/shop/*/ar/8225
Disallow: /zh-hk/shop/*/ar/8232
Disallow: /zh-hk/shop/*/ar/8224
Disallow: /zh-hk/shop/é³é »/ar/8342
Disallow: /zh-hk/shop/é»è¦åªæ /ar/8224
Disallow: /zh-hk/shop/*/ar/8225
Disallow: /zh-hk/shop/productdetailstxn/equallogic-ps4210-series
Disallow: /zh-hk/shop/povw/equallogic-ps6610-series
Disallow: /zh-hk/shop/povw/networking-wireless-ruckus-software
Disallow: /zh-hk/shop/productdetailstxn/equallogic-ps6210-series
Disallow: /zh-hk/shop/enterprise-products/sf/infiniband-switches
Disallow: /zh-hk/shop/povw/equallogic-ps-m4110
Disallow: /zh-hk/shop/productdetailstxn/poweredge-r940
Disallow: /zh-tw/*/deals/
Disallow: /zh-tw/*/deals
Disallow: /zh-tw/shop/partsbytype/printeraccessories
Disallow: /zh-tw/shop/é³é »åªæ /ar/8342
Disallow: /zh-tw/shop/ç£æ§äº¤æ/ar/8225
Disallow: /zh-tw/shop/å°æ¥ç«äº¤æ/ar/8345
Disallow: /zh-tw/shop/éæ²åªæ /ar/8244
Disallow: /zh-tw/shop/dell-ventureèå15å¯¸/apd/460-bccd/æå¸¶å
Disallow: /zh-tw/shop/ç®±ååªæ /ar/8348
Disallow: /zh-tw/shop/é»è¦éä»¶åªæ /ar/8228
Disallow: /zh-tw/shop/povw/equallogic-ps-m4110
Disallow: /learn/nz/
Disallow: /learn/sg/
Disallow: /learn/my/
Disallow: /learn/kr/
Disallow: /learn/cn/
Disallow: /learn/hk/
Disallow: /learn/tw/
Disallow: /en-us/dt/what-we-do/index-device.htm
Disallow: /en-us/dt/what-we-do/index-server.htm
Disallow: /en-us/dt/what-we-do/index-storage.htm
Disallow: /en-us/dt/what-we-do/index-apex.htm
Disallow: /support/order-status/*/order-collection
Disallow: /uk-ua

User-agent: Baiduspider
Disallow: /
Disallow: /zh-cn/cart
Disallow: /zh-cn/*/cart
Disallow: /zh-cn/buy
Disallow: /zh-cn/*/buy
Disallow: /zh-cn/*/compare
Disallow: /zh-cn/*/serviceselection/*
Disallow: /zh-cn/*/rec/*
Disallow: /zh-cn/outlet/*?
Allow: /zh-cn
Allow: /cn/
Allow: /tw/
Allow: /support/*/cn/zh/
Allow: /support/*/tw/zh/
Allow: /support/*/hk/zh/
Allow: /learn/hk/zh/
Allow: /learn/tw/zh/
Allow: /*&c=cn&*
Allow: /*?c=cn&*
Allow: /*&c=tw&*
Allow: /*?c=tw&*
Allow: /*&c=hk&*
Allow: /*?c=hk&*
Allow: /support/*/zh-cn/
Allow: /support/*/zh-tw/
Allow: /support/*/zh-hk/
Allow: /support/*/en-hk/
Allow: /zh-cn/dt/
Allow: /zh-cn/perspectives/
Allow: /zh-cn/blog/
Disallow: /zh-cn/dt/*.php$
Disallow: /zh-cn/dt/*/configuration-page.htm
Disallow: /zh-cn/dt/*/testing/
Disallow: /zh-cn/dt/*/teammembers/
Disallow: /zh-cn/dt/*/gobig
Disallow: /zh-cn/blog/*.php$
Disallow: /zh-cn/blog/*/configuration-page.htm
Disallow: /zh-cn/blog/*/testing/
Disallow: /zh-cn/blog/*/teammembers/
Disallow: /zh-cn/blog/*/gobig
Disallow: /zh-cn/perspectives/*.php$
Disallow: /zh-cn/perspectives/*/configuration-page.htm
Disallow: /zh-cn/perspectives/*/testing/
Disallow: /zh-cn/perspectives/*/teammembers/
Disallow: /zh-cn/perspectives/*/gobig
Disallow: /zh-cn/corporate/newsroom-test.htm
Disallow: /zh-cn/corporate/karen-quintos.htm
Disallow: /zh-cn/shop/äºåä¸æ¬/sf/xps-2-in-1

User-agent: Sogou web spider
Disallow: /
Allow: /zh-cn
Allow: /cn/
Allow: /tw/
Allow: /support/*/cn/zh/
Allow: /support/*/tw/zh/
Allow: /support/*/hk/zh/
Allow: /learn/hk/zh/
Allow: /learn/tw/zh/
Allow: /*&c=cn&*
Allow: /*?c=cn&*
Allow: /*&c=tw&*
Allow: /*?c=tw&*
Allow: /*&c=hk&*
Allow: /*?c=hk&
Allow: /support/*/zh-cn/
Allow: /support/*/zh-tw/
Allow: /support/*/zh-hk/
Allow: /support/*/en-hk/
Disallow: /zh-cn/outlet/*?
Allow: /zh-cn/dt/
Allow: /zh-cn/perspectives/
Allow: /zh-cn/blog/
Disallow: /zh-cn/dt/*.php$
Disallow: /zh-cn/dt/*/configuration-page.htm
Disallow: /zh-cn/dt/*/testing/
Disallow: /zh-cn/dt/*/teammembers/
Disallow: /zh-cn/dt/*/gobig
Disallow: /zh-cn/blog/*.php$
Disallow: /zh-cn/blog/*/configuration-page.htm
Disallow: /zh-cn/blog/*/testing/
Disallow: /zh-cn/blog/*/teammembers/
Disallow: /zh-cn/blog/*/gobig
Disallow: /zh-cn/perspectives/*.php$
Disallow: /zh-cn/perspectives/*/configuration-page.htm
Disallow: /zh-cn/perspectives/*/testing/
Disallow: /zh-cn/perspectives/*/teammembers/
Disallow: /zh-cn/perspectives/*/gobig
Disallow: /zh-cn/corporate/newsroom-test.htm
Disallow: /zh-cn/corporate/karen-quintos.htm
Disallow: /zh-cn/shop/äºåä¸æ¬/sf/xps-2-in-1

User-agent: Sogou inst spider
Disallow: /
Allow: /zh-cn
Allow: /cn/
Allow: /tw/
Allow: /support/*/cn/zh/
Allow: /support/*/tw/zh/
Allow: /support/*/hk/zh/
Allow: /learn/hk/zh/
Allow: /learn/tw/zh/
Allow: /*&c=cn&*
Allow: /*?c=cn&*
Allow: /*&c=tw&*
Allow: /*?c=tw&*
Allow: /*&c=hk&*
Allow: /*?c=hk&
Allow: /support/*/zh-cn/
Allow: /support/*/zh-tw/
Allow: /support/*/zh-hk/
Allow: /support/*/en-hk/
Disallow: /zh-cn/outlet/*?
Allow: /zh-cn/dt/
Allow: /zh-cn/perspectives/
Allow: /zh-cn/blog/
Disallow: /zh-cn/dt/*.php$
Disallow: /zh-cn/dt/*/configuration-page.htm
Disallow: /zh-cn/dt/*/testing/
Disallow: /zh-cn/dt/*/teammembers/
Disallow: /zh-cn/dt/*/gobig
Disallow: /zh-cn/blog/*.php$
Disallow: /zh-cn/blog/*/configuration-page.htm
Disallow: /zh-cn/blog/*/testing/
Disallow: /zh-cn/blog/*/teammembers/
Disallow: /zh-cn/blog/*/gobig
Disallow: /zh-cn/perspectives/*.php$
Disallow: /zh-cn/perspectives/*/configuration-page.htm
Disallow: /zh-cn/perspectives/*/testing/
Disallow: /zh-cn/perspectives/*/teammembers/
Disallow: /zh-cn/perspectives/*/gobig
Disallow: /zh-cn/corporate/newsroom-test.htm
Disallow: /zh-cn/corporate/karen-quintos.htm
Disallow: /zh-cn/shop/äºåä¸æ¬/sf/xps-2-in-1

User-agent: Sogou spider2
Disallow: /
Allow: /zh-cn
Allow: /cn/
Allow: /tw/
Allow: /support/*/cn/zh/
Allow: /support/*/tw/zh/
Allow: /support/*/hk/zh/
Allow: /learn/hk/zh/
Allow: /learn/tw/zh/
Allow: /*&c=cn&*
Allow: /*?c=cn&*
Allow: /*&c=tw&*
Allow: /*?c=tw&*
Allow: /*&c=hk&*
Allow: /*?c=hk&
Allow: /support/*/zh-cn/
Allow: /support/*/zh-tw/
Allow: /support/*/zh-hk/
Allow: /support/*/en-hk/
Disallow: /zh-cn/outlet/*?
Allow: /zh-cn/dt/
Allow: /zh-cn/perspectives/
Allow: /zh-cn/blog/
Disallow: /zh-cn/dt/*.php$
Disallow: /zh-cn/dt/*/configuration-page.htm
Disallow: /zh-cn/dt/*/testing/
Disallow: /zh-cn/dt/*/teammembers/
Disallow: /zh-cn/dt/*/gobig
Disallow: /zh-cn/blog/*.php$
Disallow: /zh-cn/blog/*/configuration-page.htm
Disallow: /zh-cn/blog/*/testing/
Disallow: /zh-cn/blog/*/teammembers/
Disallow: /zh-cn/blog/*/gobig
Disallow: /zh-cn/perspectives/*.php$
Disallow: /zh-cn/perspectives/*/configuration-page.htm
Disallow: /zh-cn/perspectives/*/testing/
Disallow: /zh-cn/perspectives/*/teammembers/
Disallow: /zh-cn/perspectives/*/gobig
Disallow: /zh-cn/corporate/newsroom-test.htm
Disallow: /zh-cn/corporate/karen-quintos.htm
Disallow: /zh-cn/shop/äºåä¸æ¬/sf/xps-2-in-1

User-agent: HaoSouSpider
Disallow: /
Allow: /zh-cn
Allow: /cn/
Allow: /tw/
Allow: /support/*/cn/zh/
Allow: /support/*/tw/zh/
Allow: /support/*/hk/zh/
Allow: /learn/hk/zh/
Allow: /learn/tw/zh/
Allow: /*&c=cn&*
Allow: /*?c=cn&*
Allow: /*&c=tw&*
Allow: /*?c=tw&*
Allow: /*&c=hk&*
Allow: /*?c=hk&
Allow: /support/*/zh-cn/
Allow: /support/*/zh-tw/
Allow: /support/*/zh-hk/
Allow: /support/*/en-hk/
Disallow: /zh-cn/outlet/*?
Allow: /zh-cn/dt/
Allow: /zh-cn/perspectives/
Allow: /zh-cn/blog/
Disallow: /zh-cn/dt/*.php$
Disallow: /zh-cn/dt/*/configuration-page.htm
Disallow: /zh-cn/dt/*/testing/
Disallow: /zh-cn/dt/*/teammembers/
Disallow: /zh-cn/dt/*/gobig
Disallow: /zh-cn/blog/*.php$
Disallow: /zh-cn/blog/*/configuration-page.htm
Disallow: /zh-cn/blog/*/testing/
Disallow: /zh-cn/blog/*/teammembers/
Disallow: /zh-cn/blog/*/gobig
Disallow: /zh-cn/perspectives/*.php$
Disallow: /zh-cn/perspectives/*/configuration-page.htm
Disallow: /zh-cn/perspectives/*/testing/
Disallow: /zh-cn/perspectives/*/teammembers/
Disallow: /zh-cn/perspectives/*/gobig
Disallow: /zh-cn/corporate/newsroom-test.htm
Disallow: /zh-cn/corporate/karen-quintos.htm
Disallow: /zh-cn/shop/äºåä¸æ¬/sf/xps-2-in-1

User-agent: Bytespider
Disallow: /community/*=es
Disallow: /community/*=de
Disallow: /community/*=pt
Disallow: /community/*=fr
Disallow: /community/*=ko
Disallow: /community/*=ja
Disallow: /community/*-es
Disallow: /community/*-de
Disallow: /community/*-pt
Disallow: /community/*-fr
Disallow: /community/*-ko
Disallow: /community/*-ja
User-agent: AmazonAdBot
Disallow: /community/*
User-agent: 360Spider
Disallow: /
Allow: /zh-cn
Allow: /cn/
Allow: /tw/
Allow: /support/*/cn/zh/
Allow: /support/*/tw/zh/
Allow: /support/*/hk/zh/
Allow: /learn/hk/zh/
Allow: /learn/tw/zh/
Allow: /*&c=cn&*
Allow: /*?c=cn&*
Allow: /*&c=tw&*
Allow: /*?c=tw&*
Allow: /*&c=hk&*
Allow: /*?c=hk&
Allow: /support/*/zh-cn/
Allow: /support/*/zh-tw/
Allow: /support/*/zh-hk/
Allow: /support/*/en-hk/
Disallow: /zh-cn/outlet/*?
Allow: /zh-cn/dt/
Allow: /zh-cn/perspectives/
Allow: /zh-cn/blog/
Disallow: /zh-cn/dt/*.php$
Disallow: /zh-cn/dt/*/configuration-page.htm
Disallow: /zh-cn/dt/*/testing/
Disallow: /zh-cn/dt/*/teammembers/
Disallow: /zh-cn/dt/*/gobig
Disallow: /zh-cn/blog/*.php$
Disallow: /zh-cn/blog/*/configuration-page.htm
Disallow: /zh-cn/blog/*/testing/
Disallow: /zh-cn/blog/*/teammembers/
Disallow: /zh-cn/blog/*/gobig
Disallow: /zh-cn/perspectives/*.php$
Disallow: /zh-cn/perspectives/*/configuration-page.htm
Disallow: /zh-cn/perspectives/*/testing/
Disallow: /zh-cn/perspectives/*/teammembers/
Disallow: /zh-cn/perspectives/*/gobig
Disallow: /zh-cn/corporate/newsroom-test.htm
Disallow: /zh-cn/corporate/karen-quintos.htm
Disallow: /zh-cn/shop/äºåä¸æ¬/sf/xps-2-in-1


Sitemap: https://www.dell.com/index-sr-sitemap.xml.gz
Sitemap: https://www.dell.com/index-deals-dell-sitemap.xml.gz
Sitemap: https://www.dell.com/index-content-href-sitemap.xml.gz
Sitemap: https://www.dell.com/index-deals-href-sitemap.xml.gz
Sitemap: https://www.dell.com/index-product-pages-hreflang-sitemap.xml.gz 
Sitemap: https://www.dell.com/index-sitemap.xml.gz
Sitemap: https://www.dell.com/index-snp-apj-sitemap.xml.gz
Sitemap: https://www.dell.com/index-support-href-sitemap.xml.gz
Sitemap: https://www.dell.com/index-video-xml-sitemap.xml.gz
Sitemap: https://www.dell.com/index-downloads-dell-pdfs-sitemap.xml.gz
Sitemap: https://www.dell.com/index-images-sitemap.xml.gz

# Last modified 12 July 2022