User-agent: GPTBot
Disallow: /

User-agent: *
Disallow:

Sitemap: https://www.digitalocean.com/sitemaps/community-tutorial-collections-0.xml.gz
Sitemap: https://www.digitalocean.com/sitemaps/community-tutorials-0.xml.gz
Sitemap: https://www.digitalocean.com/sitemaps/community-tutorial-series-0.xml.gz
Sitemap: https://www.digitalocean.com/sitemaps/community-questions-0.xml.gz
Sitemap: https://www.digitalocean.com/sitemaps/community-questions-1.xml.gz
Sitemap: https://www.digitalocean.com/sitemaps/community-questions-2.xml.gz
Sitemap: https://www.digitalocean.com/sitemaps/community-pages-0.xml.gz
Sitemap: https://www.digitalocean.com/sitemaps/community-tags-0.xml.gz
Sitemap: https://www.digitalocean.com/sitemaps/community-tools-0.xml.gz
Sitemap: https://www.digitalocean.com/sitemaps/community-indexes-0.xml.gz
Sitemap: https://www.digitalocean.com/sitemaps/trust-0.xml.gz
Sitemap: https://www.digitalocean.com/sitemaps/solutions-0.xml.gz
Sitemap: https://www.digitalocean.com/sitemaps/resources-0.xml.gz
Sitemap: https://www.digitalocean.com/sitemaps/resource-authors-0.xml.gz
Sitemap: https://www.digitalocean.com/sitemaps/reports-0.xml.gz
Sitemap: https://www.digitalocean.com/sitemaps/products-0.xml.gz
Sitemap: https://www.digitalocean.com/sitemaps/pricing-0.xml.gz
Sitemap: https://www.digitalocean.com/sitemaps/product-tours-0.xml.gz
Sitemap: https://www.digitalocean.com/sitemaps/landing-0.xml.gz
Sitemap: https://www.digitalocean.com/sitemaps/legal-0.xml.gz
Sitemap: https://www.digitalocean.com/sitemaps/customers-0.xml.gz
Sitemap: https://www.digitalocean.com/sitemaps/currents-0.xml.gz
Sitemap: https://www.digitalocean.com/sitemaps/companyContact-0.xml.gz
Sitemap: https://www.digitalocean.com/sitemaps/careers-0.xml.gz
Sitemap: https://www.digitalocean.com/sitemaps/blog-0.xml.gz
Sitemap: https://www.digitalocean.com/sitemaps/blog-authors-0.xml.gz
Sitemap: https://www.digitalocean.com/sitemaps/blog-tags-0.xml.gz
Sitemap: https://www.digitalocean.com/sitemaps/impact-0.xml.gz
Sitemap: https://www.digitalocean.com/sitemaps/indexes-0.xml.gz
Sitemap: https://www.digitalocean.com/sitemaps/diversity-0.xml.gz
Sitemap: https://www.digitalocean.com/sitemaps/hatch-0.xml.gz
Sitemap: https://www.digitalocean.com/sitemaps/open-source-0.xml.gz
Sitemap: https://www.digitalocean.com/sitemaps/partners-0.xml.gz
Sitemap: https://www.digitalocean.com/sitemaps/press-0.xml.gz