User-agent: *
Disallow:

Sitemap: https://www.digitalocean.com/sitemaps/community-tutorial-collections-0.xml.gz
Sitemap: https://www.digitalocean.com/sitemaps/community-tutorials-0.xml.gz
Sitemap: https://www.digitalocean.com/sitemaps/community-tutorial-series-0.xml.gz
Sitemap: https://www.digitalocean.com/sitemaps/community-questions-0.xml.gz
Sitemap: https://www.digitalocean.com/sitemaps/community-questions-1.xml.gz
Sitemap: https://www.digitalocean.com/sitemaps/community-questions-2.xml.gz
Sitemap: https://www.digitalocean.com/sitemaps/community-tags-0.xml.gz
Sitemap: https://www.digitalocean.com/sitemaps/community-pages-0.xml.gz
Sitemap: https://www.digitalocean.com/sitemaps/community-tools-0.xml.gz
Sitemap: https://www.digitalocean.com/sitemaps/community-indexes-0.xml.gz
Sitemap: https://www.digitalocean.com/sitemaps/www-trust-0.xml.gz
Sitemap: https://www.digitalocean.com/sitemaps/www-tide-0.xml.gz
Sitemap: https://www.digitalocean.com/sitemaps/www-solutions-0.xml.gz
Sitemap: https://www.digitalocean.com/sitemaps/www-resources-0.xml.gz
Sitemap: https://www.digitalocean.com/sitemaps/www-reports-0.xml.gz
Sitemap: https://www.digitalocean.com/sitemaps/www-products-0.xml.gz
Sitemap: https://www.digitalocean.com/sitemaps/www-pricing-0.xml.gz
Sitemap: https://www.digitalocean.com/sitemaps/www-landing-0.xml.gz
Sitemap: https://www.digitalocean.com/sitemaps/www-legal-0.xml.gz
Sitemap: https://www.digitalocean.com/sitemaps/www-customers-0.xml.gz
Sitemap: https://www.digitalocean.com/sitemaps/www-currents-0.xml.gz
Sitemap: https://www.digitalocean.com/sitemaps/www-contact-0.xml.gz
Sitemap: https://www.digitalocean.com/sitemaps/www-careers-0.xml.gz
Sitemap: https://www.digitalocean.com/sitemaps/www-blog-0.xml.gz
Sitemap: https://www.digitalocean.com/sitemaps/www-blog-authors-0.xml.gz
Sitemap: https://www.digitalocean.com/sitemaps/www-blog-tags-0.xml.gz
Sitemap: https://www.digitalocean.com/sitemaps/www-indexes-0.xml.gz
Sitemap: https://www.digitalocean.com/sitemaps/www-diversity-0.xml.gz
Sitemap: https://www.digitalocean.com/sitemaps/www-open-source-0.xml.gz