User-agent: AhrefsBot
Crawl-Delay: 1

User-agent: SemrushBot
Disallow: /

User-agent: MegaIndex
Disallow: /

User-agent: *
Disallow: /*_openstat
Disallow: /*utm_source
Disallow: /profile.php
Disallow: /search.php
Disallow: /search/
Disallow: /clever/
Disallow: /yummy/
Disallow: /redirect.php
Disallow: /mypersonal.php
Disallow: /captcha/
Disallow: /banned.php
Disallow: /invoice/*
Disallow: /adbanner.php
Disallow: /adbannerstat.php
Disallow: /myreg.php
Disallow: /misc/million/
Disallow: /reviews/draft/
Disallow: /reviews/ajax_io.php
Disallow: /shina/ajax_io.php
Disallow: /report/
Disallow: /credit/
Disallow: /s/
Disallow: /*comment_id=
Disallow: /poll_details.php
Disallow: /faq/*page
Disallow: /misc/comments/webview/
Host: https://www.drom.ru

Sitemap: https://www.drom.ru/sitemaps/catalog/generated/catalog_firms_index.xml
Sitemap: https://www.drom.ru/sitemaps/catalog/generated/catalog_models_index.xml
Sitemap: https://www.drom.ru/sitemaps/catalog/generated/catalog_generations_index.xml
Sitemap: https://www.drom.ru/sitemaps/catalog/generated/catalog_complectations_index.xml
Sitemap: https://www.drom.ru/sitemaps/catalog/generated/catalog_model_summary_specs_index.xml
Sitemap: https://www.drom.ru/sitemaps/catalog/generated/catalog_firm_engines_index.xml
Sitemap: https://www.drom.ru/sitemaps/catalog/generated/catalog_firm_engine_index.xml
Sitemap: https://www.drom.ru/sitemaps/catalog/generated/catalog_models_years_index.xml
Sitemap: https://www.drom.ru/sitemaps/reviews/generated/reviews_index.xml
Sitemap: https://www.drom.ru/sitemaps/reviews/generated/reviews_updates_index.xml
Sitemap: https://www.drom.ru/sitemaps/reviews/generated/reviews_years_index.xml
Sitemap: https://www.drom.ru/sitemaps/reviews/generated/reviews_firms_index.xml
Sitemap: https://www.drom.ru/sitemaps/reviews/generated/reviews_models_index.xml
Sitemap: https://www.drom.ru/sitemaps/shina/generated/shina_firms_index.xml
Sitemap: https://www.drom.ru/sitemaps/shina/generated/shina_firms_seasons_index.xml
Sitemap: https://www.drom.ru/sitemaps/shina/generated/shina_firms_sizes_seasons_index.xml
Sitemap: https://www.drom.ru/sitemaps/shina/generated/shina_model_photos_index.xml
Sitemap: https://www.drom.ru/sitemaps/shina/generated/shina_models_index.xml
Sitemap: https://www.drom.ru/sitemaps/shina/generated/shina_sizes_seasons_index.xml
Sitemap: https://www.drom.ru/sitemaps/compare/generated/compare_index.xml
Sitemap: https://www.drom.ru/sitemaps/info/generated/info_firms_index.xml
Sitemap: https://www.drom.ru/sitemaps/info/generated/info_models_index.xml
