User-agent:  *
Allow:  /
Disallow: /content/dam/fedex/brand
Disallow: /libs/
Disallow: /content/dam/fedex/us-united-states/G2M/images/2019/Q1/Walmart_Rebill_Template_559291335.xlsx
Sitemap: https://www.fedex.com/en-us/sitemap.xml
Disallow: /content/dam/fedex/us-united-states/services/US_Export_Alternative_Zoning_Rates_2018.pdf 
Disallow: /en-mm/*
Disallow: /en-ad/*
Disallow: /en-li/*
Disallow: /en-mc/*
Disallow: /en-ps/*
Disallow: /en-sm/*
Disallow: /en-yu/*
Disallow: /en-va/*
Disallow: /en-bl/*
Disallow: /en-cf/*
Disallow: /en-gq/*
Disallow: /en-gw/*
Disallow: /en-ir/*
Disallow: /en-sl/*
Disallow: /en-so/*
Disallow: /en-sd/*
Disallow: /en-sy/*
Disallow: /en-tm/*
Disallow: /en-ye/*
Disallow: /GDCMTestSites/*
Sitemap: https://www.fedex.com/global/sitemap_index.xml
Disallow: /quick-help
Disallow: /*?*
Disallow: /us/developer/WebHelp/
Disallow: /us/developer/webhelp/
Disallow: /content/dam/fedex/us-united-states/services/Case-Study-FedEx-Custom-Critical-Safe-Service-Incentive-Impacts.pdf
Disallow: /content/dam/fedex/us-united-states/services/case-study-fedex-custom-critical-safe-service-incentive-impacts.pdf
Disallow: /content/dam/fedex/us-united-states/services/Contractor-Incentives.pdf
Disallow: /content/dam/fedex/us-united-states/services/contractor-incentives.pdf
Disallow: /content/dam/fedex/us-united-states/services/EFS-Card.pdf
Disallow: /content/dam/fedex/us-united-states/services/efs-card.pdf
Disallow: /content/dam/fedex/us-united-states/services/Roadmap-Incentive.pdf
Disallow: /content/dam/fedex/us-united-states/services/roadmap-incentive.pdf
Disallow: /content/dam/fedex/us-united-states/services/Surface-Expedite-Compensation-and-Specifications.pdf
Disallow: /content/dam/fedex/us-united-states/services/surface-expedite-compensation-and-specifications.pdf
Disallow: /content/dam/fedex/us-united-states/services/WFB-TrueChoices-Overview-FAQ.pdf
Disallow: /content/dam/fedex/us-united-states/services/wfb-truechoices-overview-faq.pdf
Disallow: /content/dam/fedex/us-united-states/services/White-Glove-Compensation-and-Specifications.pdf
Disallow: /content/dam/fedex/us-united-states/services/white-glove-compensation-and-specifications.pdf
Disallow: /content/dam/fedex/us-united-states/services/Base-Plate-Program.pdf
Disallow: /content/dam/fedex/us-united-states/services/base-plate-program.pdf
Disallow: /us/oadr/en/discounts/
Disallow: /us/oadr/sp/discounts/
Allow: /Tracking?cntry_code=us
Allow: /?location=home
Allow: /locate/index.html?locale=en_US
Allow: /cn_english/?link=1
Allow: /apps/fedextrack/?action=track&cntry_code=us&freight=yes
Allow: /apps/fedextrack/?action=track
Allow: /fedextrack/?cntry_code=us&tab=1&tracknums=&clienttype=wtrk
Allow: /ratefinder/home?cc=US&language=en&locId=express
Disallow:  /en-us/brand
Disallow: /content/dam/fedex-com/legal/FCB-Service-Guide.pdf
Allow: /de/careers/?*
Allow: /global/choose-location.html?location=home
Disallow: /content/dam/fedex-com/legal/ccpa-metrics.pdf
Disallow: /content/dam/fedex/us-united-states/About/images/ConsolidatedEEO-1Reports2020.pdf
Disallow: /content/dam/fedex/us-united-states/shipping/images/printer_maintenance_guidelines.pdf
