<<<<<<< HEAD
User-Agent: *
Disallow: /cn/enterprise/
Disallow: /en/enterprise/
Disallow: /minisite/test/
Disallow: /minisite/static/
Disallow: /minisite/error
Disallow: /minisite/qr/
Disallow: /minisite/gas2015/
Disallow: /static/
Disallow: /gas2015/
Disallow: /minisite/sm-vi/
Disallow: /minisite/japan10years/
Disallow: /redirect/
Disallow: /isurvey/
Disallow: /huaweilink/
Disallow: /eox_backup/
Disallow: /iwcmmarketing/
Disallow: /w3info/
Disallow: /jp/about-huawei/publications/huawave$
Disallow: /en/products-lifecycle
Disallow: /cn/products-lifecycle
Disallow: /*/corporate/home/
Disallow: /audience/
Disallow: /enterpriseform/
Disallow: /ilink/
Disallow: /ucmf/groups/
=======
User-Agent: *
Disallow: /cn/enterprise/
Disallow: /en/enterprise/
Disallow: /minisite/test/
Disallow: /minisite/static/
Disallow: /minisite/error
Disallow: /minisite/qr/
Disallow: /minisite/gas2015/
Disallow: /static/
Disallow: /gas2015/
Disallow: /minisite/sm-vi/
Disallow: /minisite/japan10years/
Disallow: /redirect/
Disallow: /isurvey/
Disallow: /huaweilink/
Disallow: /eox_backup/
Disallow: /iwcmmarketing/
Disallow: /w3info/
Disallow: /jp/about-huawei/publications/huawave$
Disallow: /en/products-lifecycle
Disallow: /cn/products-lifecycle
Disallow: /*/corporate/home/
Disallow: /audience/
Disallow: /enterpriseform/
Disallow: /ilink/
Disallow: /ucmf/groups/
>>>>>>> c881411106adf687acaf306d655ca150e70ee17f
Disallow: /mediafiles/*