User-agent: *

Disallow: /index.php?title=MediaWiki
Disallow: /index.php?title=Special
Disallow: /index.php?title=Template
Disallow: /index.php?title=Html
Disallow: /index.php?title=Data
Disallow: /index.php?title=User
Disallow: /skins/
Disallow: /wiki/Mediawiki:
Disallow: /wiki/Special:
Disallow: /wiki/User:
Disallow: /wiki/Template:
Disallow: /wiki/DATA:
Disallow: /wiki/Html:
Disallow: /wiki/ç¹æ®:
Disallow: /wiki/ç¨æ·:
Disallow: /wiki/æ¨¡æ¿:
Disallow: /*?*action=
Disallow: /*?*feed=
Disallow: /*?*oldid=
Disallow: /*?*printable=
Disallow: /*?*variant=
Disallow: /*?*useskin=
Disallow: /*?*uselang=
Disallow: /index.php?diff=
Disallow: /index.php?oldid=
