User-agent: *
Allow: /
Disallow: /*?q=*
Disallow: */channel/flash/channel-list/*
Disallow: /next
Sitemap: https://api-gateway.dditsadn.com/v1/auth/livejasmin/en/sitemap-language-index.xml
Sitemap: https://api-gateway.dditsadn.com/v1/auth/livejasmin/es/sitemap-language-index.xml
Sitemap: https://api-gateway.dditsadn.com/v1/auth/livejasmin/de/sitemap-language-index.xml
Sitemap: https://api-gateway.dditsadn.com/v1/auth/livejasmin/fr/sitemap-language-index.xml
Sitemap: https://api-gateway.dditsadn.com/v1/auth/livejasmin/it/sitemap-language-index.xml
Sitemap: https://api-gateway.dditsadn.com/v1/auth/livejasmin/pt/sitemap-language-index.xml
Sitemap: https://api-gateway.dditsadn.com/v1/auth/livejasmin/nl/sitemap-language-index.xml
Sitemap: https://api-gateway.dditsadn.com/v1/auth/livejasmin/sv/sitemap-language-index.xml
Sitemap: https://api-gateway.dditsadn.com/v1/auth/livejasmin/no/sitemap-language-index.xml
Sitemap: https://api-gateway.dditsadn.com/v1/auth/livejasmin/da/sitemap-language-index.xml
Sitemap: https://api-gateway.dditsadn.com/v1/auth/livejasmin/fi/sitemap-language-index.xml
Sitemap: https://api-gateway.dditsadn.com/v1/auth/livejasmin/ja/sitemap-language-index.xml
Sitemap: https://api-gateway.dditsadn.com/v1/auth/livejasmin/ru/sitemap-language-index.xml
Sitemap: https://api-gateway.dditsadn.com/v1/auth/livejasmin/hu/sitemap-language-index.xml
Sitemap: https://api-gateway.dditsadn.com/v1/auth/livejasmin/cs/sitemap-language-index.xml
Sitemap: https://api-gateway.dditsadn.com/v1/auth/livejasmin/sk/sitemap-language-index.xml
Sitemap: https://api-gateway.dditsadn.com/v1/auth/livejasmin/ro/sitemap-language-index.xml
Sitemap: https://api-gateway.dditsadn.com/v1/auth/livejasmin/pl/sitemap-language-index.xml
Sitemap: https://api-gateway.dditsadn.com/v1/auth/livejasmin/zh/sitemap-language-index.xml