User-agent: *
Disallow: /s/
Disallow: /corporativo/aviso-legal.html
Disallow: /corporativo/contacto.html
Disallow: /corporativo/ayuda.html
Disallow: /multimedia/en-tu-movil/listado/index.html
Disallow: /social/
Disallow: /edicion/
Disallow: /eltiempo/
Disallow: /deporte/futbol/primera-division/2010-2011/panel-de-fichajes/*
Disallow: /eventos/marcador/futbol/2013_14/*
Disallow: /eventos/marcador/futbol/2012_13/*
Disallow: /eventos/marcador/futbol/2011_12/*
Disallow: /encuentros/roberto-palomar/2016/03/29/*
Disallow: /2012/11/03/en/football/spanish_football/1351965522.html
Disallow: /2012/11/03/futbol/1adivision/1351945508.html
Disallow: /albumes/2015/03/03/nba_malditos_muertos/*
Disallow: /rss/google/portada_google_news.xml
Disallow: /sitemaps/noticia_mx_historico*
Disallow: /sitemaps/video_mx_historico*
Disallow: /sitemaps/album_mx_historico*
Disallow: /sitemaps/cronica_mx_historico*
Disallow: /sitemaps/opinion_mx_historico*
Disallow: /apw.js*