User-agent: *
Disallow: /mb/
Disallow: /h/
Disallow: /fb/
Disallow: /lp/
Disallow: /test/
Disallow: /generator-system-config/
Disallow: /reflect/
Disallow: /google*
Disallow: /partials/
Disallow: /blog/cards/
Disallow: /blog/decks/
Disallow: /blog/members/
Disallow: /blog/forums/
Disallow: /blog/blue-tracker/
Disallow: /blog/packs/
Disallow: *?s=*
Allow: .js
Allow: .css

User-agent: Skynet
Disallow: /
