User-agent: *
Disallow: /cart/
Disallow: /search/
Disallow: /orders/
Disallow: /*-*/orders/
Disallow: /wish-list/
Disallow: /*-*/wish-list/
Disallow: /address-book/
Disallow: /*-*/address-book/

Sitemap: https://noa-prod-graph-sitemaps.s3.amazonaws.com/nintendo.com/whatsnew/sitemap.xml
Sitemap: https://noa-prod-graph-sitemaps.s3.amazonaws.com/nintendo.com/nintendo-direct/sitemap.xml
Sitemap: https://noa-prod-graph-sitemaps.s3.amazonaws.com/nintendo.com/store/sitemap.xml
Sitemap: https://noa-prod-graph-sitemaps.s3.amazonaws.com/nintendo.com/sitemap.xml
Sitemap: https://noa-prod-graph-sitemaps.s3.amazonaws.com/nintendo.com/en-ca/whatsnew/sitemap.xml
Sitemap: https://noa-prod-graph-sitemaps.s3.amazonaws.com/nintendo.com/en-ca/nintendo-direct/sitemap.xml
Sitemap: https://noa-prod-graph-sitemaps.s3.amazonaws.com/nintendo.com/en-ca/store/sitemap.xml
Sitemap: https://noa-prod-graph-sitemaps.s3.amazonaws.com/nintendo.com/en-ca/sitemap.xml
Sitemap: https://noa-prod-graph-sitemaps.s3.amazonaws.com/nintendo.com/fr-ca/whatsnew/sitemap.xml
Sitemap: https://noa-prod-graph-sitemaps.s3.amazonaws.com/nintendo.com/fr-ca/store/sitemap.xml
Sitemap: https://noa-prod-graph-sitemaps.s3.amazonaws.com/nintendo.com/fr-ca/sitemap.xml
Sitemap: https://noa-prod-graph-sitemaps.s3.amazonaws.com/nintendo.com/pt-br/whatsnew/sitemap.xml
Sitemap: https://noa-prod-graph-sitemaps.s3.amazonaws.com/nintendo.com/pt-br/store/sitemap.xml
Sitemap: https://noa-prod-graph-sitemaps.s3.amazonaws.com/nintendo.com/pt-br/sitemap.xml
Sitemap: https://noa-prod-graph-sitemaps.s3.amazonaws.com/nintendo.com/es-mx/whatsnew/sitemap.xml
Sitemap: https://noa-prod-graph-sitemaps.s3.amazonaws.com/nintendo.com/es-mx/store/sitemap.xml
Sitemap: https://noa-prod-graph-sitemaps.s3.amazonaws.com/nintendo.com/es-mx/sitemap.xml
Sitemap: https://noa-prod-graph-sitemaps.s3.amazonaws.com/nintendo.com/es-pe/whatsnew/sitemap.xml
Sitemap: https://noa-prod-graph-sitemaps.s3.amazonaws.com/nintendo.com/es-pe/store/sitemap.xml
Sitemap: https://noa-prod-graph-sitemaps.s3.amazonaws.com/nintendo.com/es-pe/sitemap.xml
Sitemap: https://noa-prod-graph-sitemaps.s3.amazonaws.com/nintendo.com/es-cl/whatsnew/sitemap.xml
Sitemap: https://noa-prod-graph-sitemaps.s3.amazonaws.com/nintendo.com/es-cl/store/sitemap.xml
Sitemap: https://noa-prod-graph-sitemaps.s3.amazonaws.com/nintendo.com/es-cl/sitemap.xml
Sitemap: https://noa-prod-graph-sitemaps.s3.amazonaws.com/nintendo.com/es-co/whatsnew/sitemap.xml
Sitemap: https://noa-prod-graph-sitemaps.s3.amazonaws.com/nintendo.com/es-co/store/sitemap.xml
Sitemap: https://noa-prod-graph-sitemaps.s3.amazonaws.com/nintendo.com/es-co/sitemap.xml
Sitemap: https://noa-prod-graph-sitemaps.s3.amazonaws.com/nintendo.com/es-ar/whatsnew/sitemap.xml
Sitemap: https://noa-prod-graph-sitemaps.s3.amazonaws.com/nintendo.com/es-ar/store/sitemap.xml
Sitemap: https://noa-prod-graph-sitemaps.s3.amazonaws.com/nintendo.com/es-ar/sitemap.xml