User-agent: *
Disallow: /?*
Disallow: /player/*
Disallow: /playlist/*
Disallow: /download/*
Disallow: /contact
Disallow: /removal
Disallow: /privacy
Disallow: /videofile/*
Disallow: /v/*
Disallow: /v$