User-agent: *
Disallow: /cdk/*
Disallow: *jsessionid*
Disallow: *tkn/*
Disallow: /mapi?*
Disallow: /?ffsputnik=*
Disallow: /?_erv=*
Disallow: /?sputnik=*
Disallow: /?cat=*
Disallow: *st.redirect*
Disallow: *cmd=logExternal*
Disallow: *?fromTime=*
Disallow: *?cmd*
Disallow: /messages/join/*
Disallow: /joincall/*
Disallow: /gifts/link/*
Disallow: /qrCode/*
Disallow: /groupcallembed/*
Clean-param: st%2Ecmd&st%2Elayer%2Ecmd&st%2E_forceSetHistory&st%2E_aid&__ref&cmn&autoplay&bonus&_cp_&promo&ad_id&group_bonus&imageId&nochat&promokey&adv_id&ref&gid&h_a&gift&1&silent&shareBonusFromPlayerGuid&st%2Eerror&st%2Eemail&_ref&auto&mute&hd&ad_level&rel&ya&textId&wmode&title&etext&auto_play&muted&fromTime&linknhung&mad&brandsafety&embed&hl&mt_link_id&tv&showinfo&refplace&st%2Erefplace&mt_creative&mt_adset&mt_click_id&mt_network&mt_campaign&mt_sub1&mt_sub2&mt_sub3&mt_sub4&mt_sub5&__dp&ip&_cl%2Eid&_clickLog&_cl%2Elist&_cl%2EsID&just-logged-in
Clean-param: st.cmd&st.layer.cmd&st._forceSetHistory&st._aid&__ref&cmn&autoplay&bonus&_cp_&promo&ad_id&group_bonus&imageId&nochat&promokey&adv_id&ref&gid&h_a&gift&1&silent&shareBonusFromPlayerGuid&st.error&st.email&_ref&auto&mute&hd&ad_level&rel&ya&textId&wmode&title&etext&auto_play&muted&fromTime&linknhung&mad&brandsafety&embed&hl&mt_link_id&tv&showinfo&refplace&st.refplace&mt_creative&mt_adset&mt_click_id&mt_network&mt_campaign&mt_sub1&mt_sub2&mt_sub3&mt_sub4&mt_sub5&__dp&ip&_cl.id&_clickLog&_cl.list&_cl.sID&just-logged-in
Clean-param: st._surl
Sitemap: https://ok.ru/sitemap-index-misc.xml.gz
Sitemap: https://ok.ru/sitemap-index-game.xml.gz
Sitemap: https://ok.ru/sitemap-index-gift.xml.gz
Sitemap: https://ok.ru/sitemap-index-content-search.xml.gz
Sitemap: https://ok.ru/sitemap-index-help.xml.gz
Sitemap: https://ok.ru/sitemap-index-user-name.xml.gz
Sitemap: https://ok.ru/sitemap-index-vip-profile.xml.gz
Sitemap: https://ok.ru/sitemap-index-vip-group.xml.gz
Sitemap: https://ok.ru/sitemap-index-profile-web.xml.gz
Sitemap: https://ok.ru/sitemap-index-group-catalog.xml.gz
Sitemap: https://ok.ru/sitemap-index-group.xml.gz
Sitemap: https://ok.ru/sitemap-index-group-topic.xml.gz
Sitemap: https://ok.ru/sitemap-index-music-artist.xml.gz
Sitemap: https://ok.ru/sitemap-index-music-album.xml.gz
Sitemap: https://ok.ru/sitemap-index-video-0.xml.gz