Sitemap: https://quillbot.com/sitemap.xml
User-agent: *
Disallow: /try
Disallow: /settings
Disallow: /extension
Disallow: /native
Disallow: /app
Disallow: /api-access
Disallow: /cdn-cgi/
Disallow: /abtest
Disallow: /recovery