Sitemap: https://quillbot.com/sitemap.xml
User-agent: *
Disallow: /try
Disallow: /settings
Disallow: /extension
Disallow: /native
Disallow: /api-access
Disallow: /cdn-cgi/
Disallow: /abtest
Disallow: /logout
Disallow: /privacy/old
Disallow: /desktop/login
Disallow: /cms-test-page
Disallow: /recovery