User-agent: *
Disallow: /cdn-cgi/l/email-protection

<<<<<<< HEAD
Sitemap: https://sitemap.rctiplus.com/kanal.xml
Sitemap: https://sitemap.rctiplus.com/extra.xml
Sitemap: https://sitemap.rctiplus.com/video.xml
Sitemap: https://sitemap.rctiplus.com/tv.xml
Sitemap: https://sitemap.rctiplus.com/news.xml
Sitemap: https://sitemap.rctiplus.com/trending.xml
Sitemap: https://sitemap.rctiplus.com/asset.xml
Sitemap: https://sitemap.rctiplus.com/info.xml
Sitemap: https://sitemap.rctiplus.com/photo.xml
Sitemap: https://sitemap.rctiplus.com/clip.xml
Sitemap: https://sitemap.rctiplus.com/episode.xml
Sitemap: https://sitemap.rctiplus.com/program.xml
Sitemap: https://sitemap.rctiplus.com/sitemap.xml
=======
Sitemap: https://sitemap.rctiplus.com/kanal.xml 
Sitemap: https://sitemap.rctiplus.com/extra.xml 
Sitemap: https://sitemap.rctiplus.com/video.xml 
Sitemap: https://sitemap.rctiplus.com/tv.xml 
Sitemap: https://sitemap.rctiplus.com/news.xml 
Sitemap: https://sitemap.rctiplus.com/trending.xml 
Sitemap: https://sitemap.rctiplus.com/asset.xml 
Sitemap: https://sitemap.rctiplus.com/info.xml 
Sitemap: https://sitemap.rctiplus.com/photo.xml 
Sitemap: https://sitemap.rctiplus.com/clip.xml 
Sitemap: https://sitemap.rctiplus.com/episode.xml 
Sitemap: https://sitemap.rctiplus.com/program.xml 
Sitemap: https://sitemap.rctiplus.com/sitemap.xml
>>>>>>> f4d6df32ea09e77e3957ddf459efdc7c995e11b4
