User-agent: *
Disallow: *-print.html$
Disallow: /sys_*
Disallow: /valdai/
Disallow: /search/
Disallow: /ria_70*
Disallow: /test_adfox*
Disallow: /ecokarta*
Disallow: /id/
Disallow: */embed/
Disallow: /specialprojects/
Disallow: /_editorial_preview_*
Disallow: /amp/*/more.html*
Disallow: /?* 
Disallow: /services/
Sitemap: https://ria.ru/sitemap_article_index.xml
Sitemap: https://ria.ru/sitemap_list_index.xml
Sitemap: https://ria.ru/sitemap_archive.xml
