User-agent: *
Disallow: /search
Disallow: /timeline
Disallow: /allbbs
Disallow: /*search_type=
Disallow: /*cate=
Disallow: /*search_key=
Disallow: /*view=
Disallow: /*orderby=
Disallow: /*range=
Disallow: /*best_tab=
Disallow: /*custom_list=
Disallow: /*m=
Disallow: /*t=