User-agent: *
Disallow: /*/d/
Disallow: /*/followers
Disallow: /*/following
Disallow: /*/pingback$
Disallow: /*/readcasts
Disallow: /*/info$
Disallow: /*/subscribers$
Disallow: /*/friends$
Disallow: /*/*/data$
Disallow: /*?format=json
Disallow: /account/
Disallow: /account-settings
Disallow: /analytics/
Disallow: /api?
Disallow: /api/
Disallow: /archive/
Disallow: /blocks?
Disallow: /blocks/
Disallow: /book_annotations/
Disallow: /book-preview/*/recommenders
Disallow: /book-preview/*/shadow_loader
Disallow: /cpds2/
Disallow: /cpspa/
Disallow: /csrf_token
Disallow: /doc-page/animated-hero-banner-recommender-props
Disallow: /doc-page/download-receipt-modal-props/
Disallow: /doc-page/embed-modal-props/
Disallow: /doc-page/exclusive-free-trial-props/
Disallow: /doc-page/flag-document-modal-props/
Disallow: /doc-page/paused-user-download-modal-props
Disallow: /doc-page/pmp-login-join-modal-props/
Disallow: /doc-page/recommenders/
Disallow: /doc-page/seo-roadblock-props/
Disallow: /doc/protected/
Disallow: /docinfo/
Disallow: /document_auxillary_content/
Disallow: /document_downloads/
Disallow: /documents/*/comments?
Disallow: /documents/search
Disallow: /embeds/
Disallow: /events/
Disallow: /explorespa/
Disallow: /feeds/user_rss/
Disallow: /fullscreen/
Disallow: /full/
Disallow: /home
Disallow: /job_game/
Disallow: /jobs/botrace_bot/
Disallow: /jobs/botrace_matches/
Disallow: /jobs/botrace_my_bots
Disallow: /jobs/botrace_rankings
Disallow: /jobs/botrace_upload_bot
Disallow: /language?
Disallow: /listen/
Disallow: /login?
Disallow: /lp-spa
Disallow: /next/
Disallow: /notifications/
Disallow: /options/exposed_to_client.js
Disallow: /payments/
Disallow: /profiles/content.json
Disallow: /profiles/more_reviews
Disallow: /profiles/timeline?
Disallow: /promo_code
Disallow: /ratings.json
Disallow: /ratings$
Disallow: /read/
Disallow: /sbd/
Disallow: /search-4gen
Disallow: /search-collections?
Disallow: /search-people?
Disallow: /search?
Disallow: /sectionized/
Disallow: /ssi/geoip_cc
Disallow: /store_purchase
Disallow: /upload-document?
Disallow: /upload/auto
Disallow: /upload/throttled
Disallow: /upload/upload_progress/
Disallow: /user_flags/
Disallow: /user-document-collections/
Disallow: /viewer/
Disallow: /word/access_denied/
Disallow: /word/add_to_favorites/
Disallow: /word/comment_login/
Disallow: /word/document_edit/
Disallow: /word/document_stats/
Disallow: /word/document_url/
Disallow: /word/download/
Disallow: /word/embed/
Disallow: /your-account

User-agent: GPTBot
Disallow: /

Sitemap: https://sitemaps.scribd.com/audiobooks_de_index.xml
Sitemap: https://sitemaps.scribd.com/audiobooks_en_index.xml
Sitemap: https://sitemaps.scribd.com/audiobooks_es_index.xml
Sitemap: https://sitemaps.scribd.com/audiobooks_fr_index.xml
Sitemap: https://sitemaps.scribd.com/audiobooks_id_index.xml
Sitemap: https://sitemaps.scribd.com/audiobooks_other_index.xml
Sitemap: https://sitemaps.scribd.com/audiobooks_pt_index.xml
Sitemap: https://sitemaps.scribd.com/audiobooks_ro_index.xml
Sitemap: https://sitemaps.scribd.com/audiobooks_ru_index.xml
Sitemap: https://sitemaps.scribd.com/books_de_index.xml
Sitemap: https://sitemaps.scribd.com/books_en_index.xml
Sitemap: https://sitemaps.scribd.com/books_es_index.xml
Sitemap: https://sitemaps.scribd.com/books_fr_index.xml
Sitemap: https://sitemaps.scribd.com/books_id_index.xml
Sitemap: https://sitemaps.scribd.com/books_other_index.xml
Sitemap: https://sitemaps.scribd.com/books_pt_index.xml
Sitemap: https://sitemaps.scribd.com/books_ro_index.xml
Sitemap: https://sitemaps.scribd.com/books_ru_index.xml
Sitemap: https://sitemaps.scribd.com/docs_de_index.xml
Sitemap: https://sitemaps.scribd.com/docs_en_index.xml
Sitemap: https://sitemaps.scribd.com/docs_es_index.xml
Sitemap: https://sitemaps.scribd.com/docs_fr_index.xml
Sitemap: https://sitemaps.scribd.com/docs_id_index.xml
Sitemap: https://sitemaps.scribd.com/docs_other_index.xml
Sitemap: https://sitemaps.scribd.com/docs_pt_index.xml
Sitemap: https://sitemaps.scribd.com/docs_ro_index.xml
Sitemap: https://sitemaps.scribd.com/docs_ru_index.xml
Sitemap: https://sitemaps.scribd.com/series_de_index.xml
Sitemap: https://sitemaps.scribd.com/series_en_index.xml
Sitemap: https://sitemaps.scribd.com/series_es_index.xml
Sitemap: https://sitemaps.scribd.com/series_fr_index.xml
Sitemap: https://sitemaps.scribd.com/series_id_index.xml
Sitemap: https://sitemaps.scribd.com/series_other_index.xml
Sitemap: https://sitemaps.scribd.com/series_pt_index.xml
Sitemap: https://sitemaps.scribd.com/series_ro_index.xml
Sitemap: https://sitemaps.scribd.com/series_ru_index.xml
Sitemap: https://sitemaps.scribd.com/sheet_music_index.xml
Sitemap: https://sitemaps.scribd.com/sheet_music_chapters_index.xml
Sitemap: https://sitemaps.scribd.com/articles_index.xml
Sitemap: https://sitemaps.scribd.com/podcasts_index.xml
Sitemap: https://sitemaps.scribd.com/snapshots_index.xml
Sitemap: https://sitemaps.scribd.com/magazines_index.xml

Sitemap: https://sitemaps.scribd.com/users_index.xml
