User-agent: *
Disallow: /*/about-us/contact/contact-spotify-password/
Disallow: /*/about-us/contact/contact-spotify-account/
Disallow: /*/get-spotify/*
Disallow: /*/xhr/*
Disallow: /*/external/*
Disallow: /*/legal/*?ets=
Disallow: /*/legal/advertiser-terms-and-conditions/
Disallow: /*/legal/gdpr-article-15-information/
Disallow: /*/account/cls/*
Disallow: /*/starbuckspartners
Disallow: /starbuckspartners
Sitemap: https://www.spotify.com/sitemap.xml
