User-agent: *
Allow: /blog/etalase
Allow: /blog/note
Allow: /blog/review
Allow: /find/*?page
Allow: /find/*/c/*?page
Allow: /find/note
Allow: /find/review
Allow: /sitemap/review
Allow: /tokopoints/intro/
Allow: /*/*/review
Disallow: */tokopedia-lite-production/
Disallow: /*.pl
Disallow: /now/*/review
Disallow: /*/*/talk
Disallow: /*/note
Disallow: /*/review
Disallow: /amp/api/*
Disallow: /archive-*
Disallow: /blog/?amp
Disallow: /cart?*
Disallow: /cart/*
Disallow: /chat?*
Disallow: /chat/*
Disallow: /content/*
Disallow: /events/search*
Disallow: /feed?sc=*
Disallow: /feedcommunicationdetail/*
Disallow: /find/*?{*
Disallow: /find/*?goldmerchant=true
Disallow: /find/*?official=true
Disallow: /find/*?shipping=*
Disallow: /find/*/c/*?{*
Disallow: /find/*/c/*?goldmerchant=true
Disallow: /find/*/c/*?official=true
Disallow: /find/*/c/*?shipping=*
Disallow: /flight/search/*
Disallow: /graphql
Disallow: /image-search/
Disallow: /insight/*
Disallow: /kartu-kredit*?id=*
Disallow: /myshop/*
Disallow: /order-list/
Disallow: /payment/*
Disallow: /people/*
Disallow: /provi/check*
Disallow: /rekomendasi/*/d/
Disallow: /reputationapp/*
Disallow: /search?*
Disallow: /search/*
Disallow: /similar-products*
Disallow: /tokopoints
Disallow: /wishlist?*
Disallow: /helios-client/*

User-agent: Yandex
Disallow: /

Sitemap: https://www.tokopedia.com/sitemap/catalog-index.xml
Sitemap: https://www.tokopedia.com/sitemap/category-index.xml
Sitemap: https://www.tokopedia.com/sitemap/cms-index.xml
Sitemap: https://www.tokopedia.com/sitemap/deals-index.xml
Sitemap: https://www.tokopedia.com/sitemap/egold-index.xml
Sitemap: https://www.tokopedia.com/sitemap/events-index.xml
Sitemap: https://www.tokopedia.com/sitemap/flight-index.xml
Sitemap: https://www.tokopedia.com/sitemap/hotel-index.xml
Sitemap: https://www.tokopedia.com/sitemap/official-store-brand-index.xml
Sitemap: https://www.tokopedia.com/sitemap/official-store-category-index.xml
Sitemap: https://www.tokopedia.com/sitemap/official-store-index.xml
Sitemap: https://www.tokopedia.com/sitemap/play-channel.xml
Sitemap: https://www.tokopedia.com/sitemap/product-find-index.xml
Sitemap: https://www.tokopedia.com/sitemap/products-index-0.xml
Sitemap: https://www.tokopedia.com/sitemap/products-index-1.xml
Sitemap: https://www.tokopedia.com/sitemap/products-index-2.xml
Sitemap: https://www.tokopedia.com/sitemap/products-index-3.xml
Sitemap: https://www.tokopedia.com/sitemap/products-index-4.xml
Sitemap: https://www.tokopedia.com/sitemap/products-index-5.xml
Sitemap: https://www.tokopedia.com/sitemap/products-index-6.xml
Sitemap: https://www.tokopedia.com/sitemap/products-index-7.xml
Sitemap: https://www.tokopedia.com/sitemap/products-index-8.xml
Sitemap: https://www.tokopedia.com/sitemap/products-index-9.xml
Sitemap: https://www.tokopedia.com/sitemap/recharge-index.xml
Sitemap: https://www.tokopedia.com/sitemap/review-index.xml
Sitemap: https://www.tokopedia.com/sitemap/salam-index.xml
Sitemap: https://www.tokopedia.com/sitemap/shop-index.xml
