User-agent: *
Disallow: /questions/
Disallow: /listtutorials/
Disallow: /listtutorial/
Disallow: /answers/
Disallow: /suggestions/
Disallow: /assets/
Disallow: /video/
Disallow: /tag/
Disallow: /abap/
Disallow: /tmp/
Disallow: /logs/
Disallow: /rate/
Disallow: /store/
Disallow: /cgi-bin/
Disallow: /videotutorials/
Disallow: /*/*_question_bank/
Disallow: //*/*/*/*/src/
Sitemap: https://www.tutorialspoint.com/sitemap_index.xml/
