User-agent: *
Disallow: /questions/qadmin
Disallow: /assets/
Disallow: /video/
Disallow: /tag/
Disallow: /abap/
Disallow: /tmp/
Disallow: /logs/
Disallow: /rate/
Disallow: /store/
Disallow: /cgi-bin/
Disallow: /videotutorials/video_course_view.php?*
Disallow: /videotutorials/course_view.php?*
Disallow: /*/*_question_bank/
Disallow: //*/*/*/*/src/
Sitemap: https://www.tutorialspoint.com/tp.xml
Sitemap: https://www.tutorialspoint.com/tp1.xml
