# Robots.txt file WebMD
# Updated 9/15/2023

User-agent: *
Disallow: */search/search_results/
Disallow: /drugs/ReportAbuse.aspx*
Disallow: */cm/
Disallow: /Share.aspx*
Disallow: /mm/
Disallow: /kapi/
Disallow: /click*
Disallow: /drugs/2/search*
Disallow: /sponsored/
Disallow: /api/
Disallow: /search/2/api/
Disallow: /webmd_static_vue/
Disallow: /aim/
Disallow: /6-tools-for-managing-your-medications
Disallow: /attr-cm-warning-signs
Disallow: /bipolar-disorder/bipolar-depression-management
Disallow: /bipolar-disorder/video/bipolar-fatherhood
Disallow: /bipolar-disorder/video/bipolar-toolbox
Disallow: /bluechew-review
Disallow: /brain/treating-gmg-video
Disallow: /brain/video/treating-gmg-video
Disallow: /breast-cancer/bc-treatment-21/provider-select
Disallow: /cbd/about-cbd
Disallow: /cbd/best-cbd-gummies-for-anxiety
Disallow: /cbd/best-cbd-oil-for-anxiety
Disallow: /cbd/best-cbd-oil-for-pain
Disallow: /cbd/best-cbd-oil-of-2023
Disallow: /cbd/best-full-spectrum-cbd-oils
Disallow: /cbd/best-gummies-of-2023
Disallow: /cbd/cbd-101-concentrated-cannabidiol
Disallow: /cbd/cbd-for-dogs
Disallow: /cbd/cbd-for-sleep
Disallow: /cbd/cbdfx-review
Disallow: /cbd/cbdistillery-review
Disallow: /cbd/koi-cbd-review
Disallow: /chemo-combo
Disallow: /cholesterol-management/high-cholesterol-treatment
Disallow: /choose-cancer-care
Disallow: /diagnosed-with-glioblastoma
Disallow: /dna
Disallow: /dna/meet-your-match
Disallow: /dna/meet-your-match-acne-prone-skin-routine
Disallow: /dna/meet-your-match-combination-to-oily-skin-routine
Disallow: /dna/meet-your-match-normal-to-dry-skin-routine
Disallow: /dupuytrens/default.htm
Disallow: /dupuytrens/treatment
Disallow: /dupuytrens/what-to-expect
Disallow: /ear-health-support/balance
Disallow: /ear-health-support/daily-care
Disallow: /ear-health-support/default.htm
Disallow: /ear-health-support/hearing-loss
Disallow: /epilepsy-seizures-rapid-rescue-single-treatment
Disallow: /friends-through-gvhd
Disallow: /gum-disease-treatment
Disallow: /hair-transplant-services
Disallow: /hims-hard-mints
Disallow: /how-caregivers-helped-loved-ones-with-attr-cm
Disallow: /knee-osteoarthritis-clinical-trial
Disallow: /lung/copd/treat-copd-21/copd-new-treatment
Disallow: /mental-health-genetic-testing
Disallow: /mother-to-baby-observational-research-studies
Disallow: /neuromyelitis-optica-spectrum-disorder-nmosd-treatment
Disallow: /nvaf-stroke-risk-treatment
Disallow: /oral-and-maxillofacial-surgeon
Disallow: /parenting/cpp-21/what-is-cpp
Disallow: /peyronies-treatment-option/talk-to-doctor
Disallow: /peyronies-treatment-option/treatment-option
Disallow: /prevent-bee-sting-allergic-reactions
Disallow: /psoriasis-plaques-biologic-medicines-targeted-therapies
Disallow: /robotic-assisted-surgery
Disallow: /straightline-cml
Disallow: /telehealth-for-women
Disallow: /treating-sleep-apnea
Disallow: /understanding-melanoma
Disallow: /video/mucinex-md
Disallow: /world-class-heart-care
Disallow: /dnastudio/default.htm
Disallow: /dnastudio/contact
Disallow: /dnastudio/about
Disallow: /dnastudio/our-work
Disallow: /multiple-sclerosis/rrms-20/monthly-rms-treatment
Disallow: /dna/the-journey-starts-now
Disallow: /ohcm
Disallow: /liver-transplant-doctor-interview
Disallow: /chronic-rare-kidney-disease-iga-nephropathy

User-agent: GPTBot
Disallow: / 
