User-agent: *
Disallow: /?*
Disallow: /downloads/
Disallow: /api/ui/
Disallow: /api/
Disallow: /ter-optout
Disallow: /pm-optout
Disallow: /wallpaper/
Disallow: /wallpapers/
Disallow: /unlisted/
Sitemap: https://wetransfer.com/sitemap.xml
