User-agent: *
Disallow: /error
Disallow: /*Search?q*
Disallow: /*search?q*
Disallow: /*results?k*
Disallow: /*Results?k*
Disallow: /_layouts/
Disallow: /_vti_bin/
Disallow: /*/contact-us?isChatCallAvailable=false
Disallow: /*/play/user/*
Sitemap: https://www.xbox.com/sitemap.xml