# *
User-agent: *

# *
User-agent: *
Disallow: /fxwidgets/
Disallow: /migration/
Disallow: /currencytransfers/

# Host
Host: https://www.xe.com/

# Sitemaps
Sitemap: https://www.xe.com/sitemap.xml
Sitemap: https://www.xe.com/sitemap-0.xml
Sitemap: https://www.xe.com/sitemap-1.xml
Sitemap: https://www.xe.com/sitemap-2.xml
Sitemap: https://www.xe.com/sitemap-3.xml
Sitemap: https://www.xe.com/sitemap-4.xml
Sitemap: https://www.xe.com/sitemap-5.xml
Sitemap: https://www.xe.com/sitemap-6.xml
Sitemap: https://www.xe.com/sitemap-7.xml
Sitemap: https://www.xe.com/sitemap-8.xml
Sitemap: https://www.xe.com/sitemap-9.xml
Sitemap: https://www.xe.com/sitemap-10.xml
Sitemap: https://www.xe.com/sitemap-11.xml
Sitemap: https://www.xe.com/sitemap-12.xml
Sitemap: https://www.xe.com/sitemap-13.xml
Sitemap: https://www.xe.com/sitemap-14.xml
Sitemap: https://www.xe.com/sitemap-15.xml
Sitemap: https://www.xe.com/sitemap-16.xml
Sitemap: https://www.xe.com/sitemap-17.xml
Sitemap: https://www.xe.com/sitemap-18.xml
Sitemap: https://www.xe.com/sitemap-19.xml
Sitemap: https://www.xe.com/sitemap-send-money.xml
Sitemap: https://www.xe.com/sitemap-business.xml
Sitemap: https://www.xe.com/partnerships/sitemap.xml
Sitemap: https://www.xe.com/blog/sitemap.xml
Sitemap: https://www.xe.com/company/sitemap.xml
