User-Agent: *
Allow: /
Disallow: /content/xero/
Disallow: /media/
Disallow: /content/dam/*.pptx$
Disallow: /content/dam/*.pdf$
Disallow: /content/dam/*.docx$
Disallow: /downloads/*

Sitemap: https://www.xero.com/sitemapindex.xml
Sitemap: https://www.xero.com/au/sitemap.xml
Sitemap: https://www.xero.com/hk/sitemap.xml
Sitemap: https://www.xero.com/id/sitemap.xml
Sitemap: https://www.xero.com/ie/sitemap.xml
Sitemap: https://www.xero.com/sitemap.xml
Sitemap: https://www.xero.com/my/sitemap.xml
Sitemap: https://www.xero.com/nz/sitemap.xml
Sitemap: https://www.xero.com/ph/sitemap.xml
Sitemap: https://www.xero.com/sg/sitemap.xml
Sitemap: https://www.xero.com/uk/sitemap.xml
Sitemap: https://www.xero.com/za/sitemap.xml
Sitemap: https://www.xero.com/us/sitemap.xml
Sitemap: https://www.xero.com/ca/sitemap.xml