User-agent: *
Disallow: /p/
Disallow: /r/
Disallow: /bin/
Disallow: /caas/
Disallow: /blank.html
Disallow: /includes/
Disallow: /_td_api
Disallow: /tdv2_fp
Disallow: /nel_ms
Disallow: /fp_ms
Disallow: /sports_fp_ms
Disallow: /search_ms
Disallow: /_tdpp_api
Disallow: /_remote
Disallow: /_multiremote
Disallow: /_tdhl_api
Disallow: /digest
Disallow: /fpjs
Disallow: /myjs

Sitemap: https://www.yahoo.com/sitemap/fp-sitemap_index_US_en-US.xml.gz
Sitemap: https://www.yahoo.com/gma/sitemaps/gma-sitemap_index_US_en-US.xml.gz
Sitemap: https://www.yahoo.com/entertainment/sitemaps/entertainment-sitemap_index_US_en-US.xml.gz
Sitemap: https://www.yahoo.com/entertainment/sitemaps/entertainment-sitemap_googlenewsindex_US_en-US.xml.gz
Sitemap: https://www.yahoo.com/lifestyle/sitemaps/lifestyles-sitemap_index_US_en-US.xml.gz
Sitemap: https://www.yahoo.com/lifestyle/sitemaps/lifestyle-sitemap_googlenewsindex_US_en-US.xml.gz
Sitemap: https://www.yahoo.com/subscriptions/sitemap.xml
Sitemap: https://www.yahoo.com/news/weather/sitemap.xml
Sitemap: https://www.yahoo.com/sitemap-uh.xml
Sitemap: https://www.yahoo.com/news/sitemaps/news-sitemap_index_US_en-US.xml.gz
Sitemap: https://www.yahoo.com/news/sitemaps/news-sitemap_googlenewsindex_US_en-US.xml.gz
Sitemap: https://www.yahoo.com/topics/sitemaps/topics-sitemap_index_US_en-US.xml.gz
Sitemap: https://www.yahoo.com/games/sitemaps/sitemap_en-us.xml
